<<MavenRepositoryScanner>>
[[MavenRepositoryScanner]]
== Scanner for remote maven repositories
Downloads the repository index and retrieves all available new artifacts for scanning.

This plugin should be triggered on the command line by providing an URL and a specific scope:

Examples: 
[source,bash]
----
>jqassistant.cmd scan -u maven:repository::http://[<user>:<password>@]<repository url>
>jqassistant.cmd scan -u maven:repository::http://foo:bar@example.com/m2repo
----

TIP: The plugin supports incremental runs on a maven repository. In this case only new artifacts will be downloaded and
scanned. Old snapshot artifacts will be handled as predecessors (see below). Note that such predecessor artifacts will
have no direct relationship to the :Maven:Repository node.

TIP: For incremental scanning it is necessary that the exactly the same URL is provided on sub-sequent scans.

=== Configuration

.Configuration properties
[options="header"]
|====
| Property     			 | Description																		   | Default
| m2repo.directory 		 | A directory path. This directory is the target for Maven indices and artifacts. 	   | ./jqassistant/data/m2repo
| m2repo.filter.includes | A comma separated list of artifact patterns to include in the scan                  | include all artifacts
| m2repo.filter.excludes | A comma separated list of artifact patterns to exclude from the scan                | exclude no artifacts
| m2repo.artifacts.scan  | A boolean value. If true then the content of the artifacts is scanned.              | true
| m2repo.artifacts.keep  | A boolean value. If true then all downloaded artifacts where deleted after scanning.| false
|====

TIP: The artifact patterns follow the Maven syntax, i.e. "[groupId]:[artifactId]:[type]:[version]" or "[groupId]:[artifactId]:[type]:[classifier]:[version]" and allow using wildcards.

=== :Maven:Repository
A remote Maven repository.

.Properties of :Maven:Repository
[options="header"]
|====
| Name      	| Description
| url 			| the remote URL
| lastUpdate	| timestamp of the last scan
|====

.Relations of :Maven:Repository
[options="header"]
|====
| Name              | Target label(s)            | Cardinality | Description
| CONTAINS_POM      | <<:Maven:Pom:Xml>>  | 0..n | References the POMs in the repository
| CONTAINS_ARTIFACT | <<:Maven:Artifact>> | 0..n | References the artifacts in the repository
|====

<<MavenArtifactScanner>>
[[MavenArtifactScanner]]
== Scanner for remote maven artifacts
Gets the maven artifact coordinates to retrieve the artifact from an repository and scans it. The scanner accepts org.apache.maven.index.ArtifactInfo-Items 
with the scope "maven:repository".

NOTE: This plugin needs some prerequisites to work properly. The context must contain a MavenRepositoryDescriptor to which the new Maven Artifact belongs and an
ArtifactProvider-Object to load the artifact from the configured repository.

