//
//
//

[.lead]
The jQAssistant YAML 2 Plugin allows jQAssistant scan
YAML documents and to build a graph model out of any
valid YAML 1.2 document.

The YAML 2 Plugin is the successor of the jQAssistant
YAML Plugin which suffers from a faulty graph model.
As soon the YAML 2 Plugin is ready for production,
it will replace the YAML Plugin.

[TIP]
It is highly recommended to read the {yamlSpec}[YAML 1.2 specification]
and to become more familiar with the possibilities of YAML.

[discrete]
== Features

* Support of {yamlSpec}[YAML 1.2 specification^]
* Full support for maps, scalars,and sequences
* Support of aliases and anchors

[discrete]
== Feature Requests and Bugs

In case of a missing feature or any kind of unexpected or
faulty behaviour, please
https://github.com/jqassistant/jqa-yaml2-plugin/issues[file an issue via Github^].


[discrete]
== Compatibility with the jQAssistant YAML Plugin

The graph model build by the YAML 2 Plugin is totally different
from the one of the YAML Plugin and not compatible. Therefore
existing contraints and reports, which make use of the graph
model generated by the previous plugin must be reworked.


