//
//
//

[.lead]
The jQAssistant YAML 2 Plugin allows jQAssistant scan
YAML documents and to build a graph model out of any
valid YAML 1.2 document.

The YAML 2 Plugin is the successor of the jQAssistant
YAML Plugin which suffers from a faulty graph model.
As soon the YAML 2 Plugin is ready for production,
it will replace the YAML Plugin.

[TIP]
It is highly recommended to read the {yamlSpec}[YAML 1.2 specification]
and to become more familiar with the possibilities of YAML.

[discrete]
== Features

* Support of {yamlSpec}[YAML 1.2 specification^]
* Full support for maps, scalars,and sequences
* Support for aliases and anchors

[discrete]
== Feature Requests and Bugs

In case of a missing feature or any kind of unexpected or
faulty behaviour, please
https://github.com/jqassistant/jqa-yaml2-plugin/issues[file an issue via Github^].

[discrete]
== Configuration

.Configuration properties
[options="header", cols="1,3"]
|====
| Property
| Description

| `yaml.file.include`
a| A comma separated list of file name patterns, wildcards (?,\*) are allowed,
e.g. `/playbooks/*`, and work recursively if you they cover directories.

[NOTE]
The default value is `*.yaml, *.yml`.
If you override the value and want the defaults to be scanned as well, you have to explicitely list them in the `yaml.file.include` patterns.

| `yaml.file.exclude`
| A comma separated list of file name patterns, wildcards (?,\*) are allowed,
e.g. `*.j2`.
|====

[discrete]
== Compatibility with the jQAssistant YAML Plugin

The graph model build by the YAML 2 Plugin is different
from the one of the YAML Plugin and not compatible. Therefore,
existing constraints and reports, which make use of the graph
model generated by the previous plugin must be reworked.
