package com.buschmais.jqassistant.plugin.java.api.model;

import com.buschmais.xo.api.annotation.Abstract;
import com.buschmais.xo.neo4j.api.annotation.Label;

/**
 * Defines label "Java" which is applied to all nodes generated by this plugin.
 */
@Abstract
@Label("Java")
public interface JavaDescriptor {
}
