package com.buschmais.jqassistant.core.scanner.api;

import java.io.IOException;

import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.project.MavenProject;

import com.buschmais.jqassistant.core.store.api.Store;
import com.buschmais.jqassistant.core.store.api.descriptor.ProjectDescriptor;

/**
 * Defines the interface for plugins for scanning project.
 * 
 * @param <T>
 *            The type of descriptors generated by this plugin.
 */
public interface ProjectScannerPlugin<T extends ProjectDescriptor> extends ScannerPlugin {

	/**
	 * Perform scanning of a project.
	 * 
	 * @param store
	 *            The {@Store}.
	 * @param project
	 *            The {@MavenProject}.
	 * @return The descriptor representing the file.
	 * @throws MojoExecutionException
	 * @throws IOException
	 *             If scanning fails.
	 */
	T scanProject(Store store, MavenProject project) throws IOException;
}
