package com.buschmais.jqassistant.core.scanner.api;

import java.io.File;
import java.io.IOException;
import java.util.Collection;

import org.apache.maven.project.MavenProject;

import com.buschmais.jqassistant.core.store.api.Store;
import com.buschmais.jqassistant.core.store.api.descriptor.Descriptor;

/**
 * Defines the interface for plugins for scanning project.
 * 
 * @param <T>
 *            The type of descriptors generated by this plugin.
 */
public interface ProjectScannerPlugin<T extends Descriptor> extends ScannerPlugin {

	/**
	 * Perform scanning of a project.
	 * 
	 * @param store
	 *            The {@Store}.
	 * @param project
	 *            The {@MavenProject}.
	 * @return The descriptor representing the file.
	 * @throws IOException
	 *             If scanning fails.
	 */
	T scanProject(Store store, MavenProject project);

	/**
	 * @return
	 */
	Collection<? extends File> getAdditionalFiles();
}
