version: 2
updates:
  - package-ecosystem: 'maven'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '00:00'
    open-pull-requests-limit: 15
    labels:
      - 'area: dependencies'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '00:00'
    open-pull-requests-limit: 10
    labels:
      - 'area: dependencies'
