name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '✨ Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'

change-template: '- $TITLE (#$NUMBER by @$AUTHOR)'
change-title-escapes: '\<*_&'
# You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
exclude-labels:
  - 'skip-changelog'
template: |
  ## What's changed

  $CHANGES
autolabeler:
  - label: 'chore'
    branch:
      - '/chore\/.+/'
  - label: 'bug'
    branch:
      - '/bug\/.+/'
      - '/bugfix\/.+/'
      - '/hotfix\/.+/'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
