= jQAssistant
jQAssistant Developer Team <info@jqassistant.org>

Your Software. Your Structures. Your Rules.

This document describes the concepts of jQAssistant and usage information.

:numbered!:
[abstract]
== Overview

jQAssistant is a tool supporting the process for developing Java applications. It is based on the graph database http://neo4j.org[Neo4j] and
can be plugged into the Maven build process to break the build on detection of constraint violations and generate reports about user defined
concepts and metrics.

Here are some use cases

- Enforce naming conventions, e.g. EJBs, JPA entities, test classes, packages, maven modules etc.
- Validate dependencies between modules of your project
- separate API and implementation classes (e.g. a module must only have dependencies to API classes of other components)
- detect common problems, e.g cyclic dependencies, tests without assertions, etc.

The rules are specified using Cypher - the Neo4j query language:

[source]
----
match
  (t:Test:Method)
where not
  (t)-[:INVOKES]->(:Assert:Method)
return
  t as TestWithoutAssertion
----

== License
jQAssistant is contributed under http://www.apache.org/licenses/LICENSE-2.0[Apache License 2.0].

include::quickstart.adoc[]

include::{docRoot}/jqassistant-maven-plugin/readme.adoc[]

////
include::{docRoot}/jqassistant.scm.cli/readme.adoc[]
////

include::examples.adoc[]

include::plugins.adoc[]

////
include::devguide.adoc[]
////