= jQAssistant
jQAssistant Developer Team <dev@jqassistant.org>

Your Software. Your Structures. Your Rules.

This document describes the concepts of jQAssistant and usage information.

:numbered!:
[abstract]
== Introduction

jQAssistant is a tool supporting the process for developing Java applications. It is based on the graph database http://neo4j.org[Neo4j] and
can be plugged into the Maven build process to break the build on detection of constraint violations and generate reports about user defined
concepts and metrics.

Here are some examples:

- Enforce naming conventions, e.g. EJBs, JPA entities, test classes, package names etc.
- Define business modules (e.g. shopping cart, user management) and technical modules (e.g. presentation, business logic, persistence) and validate dependencies between them
- separate APIs and implementation classes (e.g. a module must only have dependencies to API classes of other components)
- detect common problems, e.g cyclic package dependencies, dead code

== License
jQAssistant is contributed under http://www.apache.org/licenses/LICENSE-2.0[Apache License 2.0].

include::{docRoot}/jqassistant-maven-plugin/readme.adoc[]

////
include::{docRoot}/jqassistant.scm.cli/readme.adoc[]
////

include::examples.adoc[]

include::plugins.adoc[]

////
include::devguide.adoc[]
////