jqassistant:
  plugins:
    - group-id: com.buschmais.jqassistant.build
      artifact-id: jqassistant
      version: ${jqassistant.build.version}
    - group-id: org.jqassistant.plugin
      artifact-id: jqassistant-sarif-report-plugin
      version: 1.0.0-M1
  scan:
    include:
      files:
        - ${project.basedir}/readme.adoc
        - ${project.basedir}/src/main/asciidoc
        - ${project.basedir}/.editorconfig
        - ${project.basedir}/LICENSE
  analyze:
    rule:
      default-concept-severity: INFO
    groups:
      - jqa-*
    report:
      continue-on-failure: true
      properties:
        sarif:
          report:
            message:
              text: title
              markdown: details

