
== Maven Plugin

jQAssistant provides a plugin for http://maven.apache.org[Apache Maven] which can be used to provide either fully automated scanning and analysis during the build
process or manual execution from a command line.

=== Setup
[[ProjectScope]]
==== Project Scope

Software projects often consist of several modules which are assembled to executable or deployable artifacts. In a Maven project, these modules
are usually organized hierarchically with a common parent module which is referenced directly or indirectly by all sub-modules. For each
project, jQAssistant uses a separate database with its own set of rules. Thus if a goal is executed within a Maven structure jQAssistant
first determines the project scope, i.e. the root module, by searching within the tree starting from the current module following the
parent relation until either a module is found where a directory "jqassistant/" exists or no parent is defined. The determined root module
defines the location of

- the set of rules to apply (from the directory "jqassistant/")
- the database, default "{project.build.directory}/jqassistant/store"
- the generated native report, default: "{project.build.directory}/jqassistant/jqassistant-report.xml")
- and the generated HTML report, default "{project.build.directory}/site/jqassistant.html")

The following examples demonstrate different scenarios, the root modules as detected by jQAssistant are marked using asterisks.

.Single project consisting of two modules
[source]
----
root*
   |-pom.xml
   |
   |-jqassistant
   |           |-rules.xml
   |
   |-module1
   |       |-pom.xml
   |
   |-module2
           |-pom.xml
----

.Multiple projects, each consisting of two modules
[source]
----
root
   |-pom.xml
   |
   |-project1*
   |        |-jqassistant
   |        |           |-rules1.xml
   |        |
   |        |-pom.xml
   |        |-module1
   |        |       |-pom.xml
   |        |
   |        |-module2
   |                |-pom.xml
   |
   |-project2*
            |-jqassistant
            |           |-rules2.xml
            |-pom.xml
            |-module1
            |       |-pom.xml
            |
            |-module2
                    |-pom.xml
----

NOTE: The described mechanism is designed to work for Maven module structures which are organized in hierarchies with
consistent parent relations. For other setups, it is possible to enforce using the module where the mvn goal is invoked
as root module by setting the configuration option <<useExecutionRootAsProjectRoot>>.

==== Plugin Configuration

The jQAssistant Maven plugin must be configured in the pom.xml of the root module, it should not be overwritten by sub-modules.

.Setup of the jQAssistant Maven plugin including supported configuration options and their default values (within comments).
[source,xml]
----
<project ...>
    ...
    <build>
        <plugins>
            <plugin>
                <groupId>@{project.groupId}</groupId>
                <artifactId>@{project.artifactId}</artifactId>
                <version>@{project.version}</version>
                <executions>
                    <execution>
                        <!-- The id "default-cli" is used to allow execution of the goals with the given configuration from the command line -->
                        <id>default-cli</id>
                        <goals>
                            <goal>scan</goal>
                            <goal>analyze</goal>
                        </goals>
                        <!--
                        <extensions>false</extensions>
                        -->
                        <configuration>
                        <!-- Store/Database -->
                            <!--
                            <store>
                                <uri>file:target/jqassistant/store</uri>
                                <username></username>
                                <password></password>
                                <encryption>false</encryption>
                                <trustStrategy></trustStrategy>
                                <trustCertificate></trustCertificate>
                                <embedded>
                                  <listenAddress>localhost</listenAddress>
                                  <httpPort>7474</httpPort>
                                  <boltPort>7687</boltPort>
                                </embedded>
                            </store>
                            <storeLifecycle>REACTOR</storeLifecycle>
                             -->

                        <!-- Scan -->
                            <!--
                            <reset>true</reset>
                            <scanIncludes>
                                <scanInclude>
                                    <path>config</path>
                                </scanInclude>
                                <scanInclude>
                                    <path>${project.build.directory}/extra-classes</path>
                                    <scope>java:classpath</scope>
                                </scanInclude>
                                <scanInclude>
                                    <url>https://repo1.maven.org/maven2</url>
                                    <scope>maven:repository</scope>
                                </scanInclude>
                            </scanIncludes>
                            <scanProperties>
                                <customScanner.property>value</customScanner.property>
                            </scanProperties>
                            <continueOnError>false</continueOnError>
                            -->

                        <!-- Analysis configuration -->
                            <!--
                            <warnOnSeverity>MINOR</warnOnSeverity>
                            <failOnSeverity>MAJOR</failOnSeverity>
                            <continueOnFailure>true</continueOnFailure>
                            <concepts>
                                <concept>junit4:TestClass</concept>
                            </concepts>
                            <constraints>
                                <constraint>junit4:TestMethodWithoutAssertion</constraint>
                            </constraints>
                            <groups>
                                <group>default</group>
                            </groups>
                            <ruleParameters>
                                <myRuleParameter>com.buschmais</myRuleParameter>
                            </ruleParameters>
                            <rule>
                                <defaultConceptSeverity>MINOR</defaultConceptSeverity>
                                <defaultConstraintSeverity>MAJOR</defaultConstraintSeverity>
                                <defaultGroupSeverity></defaultGroupSeverity>
                            </rule>
                            <rulesDirectory>jqassistant</rulesDirectory>
                            <rulesDirectories>
                                <rulesDirectory>${project.build.directory}/generated-rules</rulesDirectory>
                            </rulesDirectories>
                            -->

                        <!-- Report -->
                            <!--
                            <reportProperties>
                                <customReport.fileName>
                                    ${project.build.directory}/customReport.txt
                                </customReport.fileName>
                            </reportProperties>
                            <attachReportArchive>false</attachReportArchive>
                            <xmlReportFile>${project.build.directory}/jqassistant/jqassistant-report.xml</xmlReportFile>
                            -->

                        <!-- Misc -->
                            <!--
                            <skip>false</skip>
                            <useExecutionRootAsProjectRoot>false</useExecutionRootAsProjectRoot>
                            -->
                         </configuration>
                    </execution>
                </executions>
                <!-- Plugins are declared as dependencies of the Maven plugin -->
                <!--
                <dependencies>
                    <dependency>
                        <groupId>org.jqassistant.contrib.plugin</groupId>
                        <artifactId>jqassistant-test-impact-analysis-plugin</artifactId>
                        <version>1.0.0</version>
                    </dependency>
                </dependencies>
                -->
            </plugin>
        </plugins>
    </build>

    <!-- The following section is only required if a Maven site shall be generated including a jQAssistant report -->
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <version>3.0.0</version>
            </plugin>
            <plugin>
                <groupId>@{project.groupId}</groupId>
                <artifactId>@{project.artifactId}</artifactId>
                <version>@{project.version}</version>
                <reportSets>
                    <reportSet>
                        <reports>
                            <report>report</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
        </plugins>
    </reporting>
    ...
</project>
----

==== Command Line

Goals may also be executed from the command line:

[source]
----
mvn ${project.groupId}:${project.artifactId}:available-rules
----

Adding the following lines to the file settings.xml (usually located in the $HOME/.m2) eases execution of jQAssistant goals from the command line:

[source,xml]
----
<pluginGroups>
    <pluginGroup>com.buschmais.jqassistant</pluginGroup>
</pluginGroups>
----

The same goal can now be executed using the following command line statement:

[source]
----
mvn jqassistant:available-rules
----

=== Goals

* <<scan>>
* <<available-scopes>>
* <<reset>>
* <<server>>
* <<analyze>>
* <<effective-rules>>
* <<available-rules>>
* <<report>>

[[scan]]
==== jqassistant:scan
===== Description
Scans the project directories according to the given configuration (e.g. compiled classes and test classes) and stores the
gathered information in the database.

===== Configuration

* <<skip>>
* <<useExecutionRootAsProjectRoot>>
* <<store>>
* <<storeLifecycle>>
* reset (-Djqassistant.store.reset)
** indicates whether the store shall be reset (i.e. cleaned up) before scanning
** default: 'true'
* scanIncludes
** add directories, files or URLs to be included while scanning (optionally qualifed with a scope)
** wildcards are not supported
* scanProperties
** allows passing properties to scanner plugins
* continueOnError
** continue scanning even if a plugin fails with an unrecoverable error
** default: `false`

WARNING: Using 'continueOnError' might create inconsistent data.
Any reported errors should be reported to the plugin developer.

[[available-scopes]]
==== jqassistant:available-scopes
===== Description
List all available scopes which may be specified for scanInclude properties.

[[reset]]
==== jqassistant:reset
===== Description
Resets the database by deleting all nodes and relationships.

===== Configuration
* <<skip>>
* <<useExecutionRootAsProjectRoot>>
* <<store>>
* <<storeLifecycle>>

[[server]]
==== jqassistant:server
===== Description
Starts the integrated Neo4j web server (default address: http://localhost:7474).

===== Configuration
* <<skip>>
* <<useExecutionRootAsProjectRoot>>
* <<store>>
* <<storeLifecycle>>

[[analyze]]
==== jqassistant:analyze
===== Description
Executes an analysis.

===== Configuration
* <<skip>>
* <<useExecutionRootAsProjectRoot>>
* <<store>>
* <<storeLifecycle>>
* <<rule>>
* <<concepts>>
* <<constraints>>
* <<groups>>
* <<rulesDirectory>>
* <<rulesDirectories>>
* <<rulesUrl>>
* <<xmlReportFile>>
* warnOnSeverity (-Djqassistant.warnOnSeverity)
** determines the severity level for issuing warnings for failed with equal or higher severities
** default: 'MINOR'
* failOnSeverity (-Djqassistant.failOnSeverity)
** determines the severity level for breaking the build if at least one rule with an equal or higher severity failed
** default: 'MAJOR'
* continueOnFailure
** Determines if jQAssistant shall continue the build if failures have been detected
* executeAppliedConcepts (-Djqassistant.executeAppliedConcepts)
** Execute concepts which have already been applied before. The default is 'false' to save time on repeated runs of "analyze" on the
   same data. Setting this flag to 'true' is useful for creating and trying out new concepts.
** default 'false'
* ruleParameters
** The values for rules that require parameters
* reportProperties
** The properties to be passed to report plugins
* attachReportArchive
** If `true` a ZIP file `jqassistant-report.zip` containing the generated reports is created in the folder
   `target/jqassistant` of the root module and attached using the classifier `jqassistant-report`.

NOTE: If for a multi-module project the report archive shall be installed into the local repository the https://maven.apache.org/plugins/maven-install-plugin/install-mojo.html[Maven Install Plugin]
      must be configured to use `installAtEnd`.
      In a similar way for deploying the report archive to a remote repository `deployAtEnd` must be actived for the https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html[Maven Deploy Plugin].


[[effective-rules]]
==== jqassistant:effective-rules
===== Description
List the rules which would be executed for an analysis and the given concepts, constraints or groups.

===== Configuration
* <<skip>>
* <<concepts>>
* <<constraints>>
* <<groups>>
* <<useExecutionRootAsProjectRoot>>
* <<rulesDirectory>>
* <<rulesDirectories>>
* <<rulesUrl>>

[[available-rules]]
==== jqassistant:available-rules
===== Description
List all available rules.

===== Configuration
* <<skip>>
* <<useExecutionRootAsProjectRoot>>
* <<rulesDirectory>>
* <<rulesDirectories>>
* <<rulesUrl>>

[[report]]
==== jqassistant:report
===== Description
Transforms the XML report into HTML (i.e. for generating a Maven site).

===== Configuration
* <<xmlReportFile>>

=== Common Configuration Properties
==== Execution

[[skip]]
===== skip (-Djqassistant.skip)
* skip execution of the plugin
* default: 'false'

[[useExecutionRootAsProjectRoot]]
===== useExecutionRootAsProjectRoot (-Djqassistant.useExecutionRootAsProjectRoot)
* force the module where 'mvn' is being executed to be used as root module
** the database will be created in this module and contain all information of the reactor
** rules will be read from the <<rulesDirectory>> of this module
* default: 'false'

==== Store

[[store]]
===== store
* specifies the configuration of the database to use
* uri (-Djqassistant.store.uri)
** URI of the database, supported URI schemes are
** 'file' for embedded databases, e.g. 'file:target/mystore'
** 'bolt' for connecting to a running Neo4j instance (3.x+), e.g. 'bolt://localhost:7687'
* username (-Djqassistant.store.username)
** the username 'bolt' connections
* password (-Djqassistant.store.password)
** the password for 'bolt' connections
* encryption (-Djqassistant.store.encryption)
** the encryption level for 'bolt' connections: `false` (default) or `true`
* trustStrategy (-Djqassistant.store.trustStrategy)
** the trust strategy for  'bolt' connections: `trustAllCertificates` (default), `trustCustomCaSignedCertificates` or `trustSystemCaSignedCertificates`
* trustCertificate (-Djqassistant.store.trustCertificate)
** the file containing the custom CA certificate for trust strategy `trustCustomCaSignedCertificates`
* default: use embedded database at 'file:{rootModule}/target/jqassistant/store'
* <<embedded>>

[[embedded]]
===== embedded
* the configuration of the embedded Neo4j store
* listenAddress (-Djqassistant.embedded.listenAddress)
** the listen address to use for opening BOLT/HTTP connections
** default: `localhost`
* httpPort (-Djqassistant.embedded.httpPort)
** the HTTP port to be used by the Neo4j server
** default: `7474`
* boltPort (-Djqassistant.embedded.boltPort)
** the BOLT port to be used by the Neo4j server
** default: `7687`

[[storeDirectory]]
===== storeDirectory (-Djqassistant.store.directory)
* specifies the location of the database, either a relative path to the root module directory or an absolute path
* default: '{rootModule}/target/jqassistant/store'

[[storeLifecycle]]
===== storeLifecycle (-Djqassistant.store.lifecycle)
* specifies the lifecycle of the data store
** 'REACTOR': cache the store for the execution time of the reactor for fast execution
** 'MODULE': open and close the store for each module, slower but required for maven reactors containing extensions
* default: 'REACTOR'

==== Analysis And Report

[[concepts]]
===== concepts (-Djqassistant.concepts)
* specifies the ids of the concepts to be applied

[[constraints]]
===== constraints (-Djqassistant.constraints)
* specifies the ids of the constraints to be validated

[[groups]]
===== groups (-Djqassistant.groups)
* specifies the ids of the groups to be executed
* default: 'default'

[[rule]]
===== rule
* specifies rule-related settings
* defaultConceptSeverity
** the default severity of concepts without an explicit severity
** default: 'MINOR'
* defaultConstraintSeverity
** the default severity of constraints without an explicit severity
** default: 'MAJOR'
* defaultGroupSeverity
** the default severity of groups without an explicit severity
** default: none

[[rulesDirectory]]
===== rulesDirectory (-Djqassistant.rules.directory)
* specifies the name of the directory which contains rules
* this directory is also used to identify the root module of a project, see <<ProjectScope>>
* default: 'jqassistant'

[[rulesDirectories]]
===== rulesDirectories (-Djqassistant.rules.directories)
* specifies a list of directory names relative to the root module containing additional rules

[[rulesUrl]]
===== rulesUrl <url> (-Djqassistant.rules.url)
* specifies the URL of a file containing rules
* this option is exclusive, i.e. it will disable loading rules from plugins or rule directories

[[xmlReportFile]]
===== xmlReportFile (-Djqassistant.report.xml)
* specifies the target file for writing the XML report
* default: '{rootModule}/target/jqassistant/jqassistant-report.xml'
