
= Plugin for Maven

== 2.1.0

* Automatically select embedded Neo4j version depending on Java runtime: Neo4j 4.x for JDK 11, Neo4j 5.x for JDK 17 or later

== 2.0.8

* Added configuration property `jqassistant.maven.module.skip` to skip module level goals (e.g. `scan`) without affecting project level goals (e.g. `analyze`)

== 2.0.7

* Added goal `jqassistant:effective-configuration` to print the current configuration as YAML representation on the console

== 2.0.5

* The goal `jqassistant:report` no longer creates empty an HTML report for Maven modules without `jqassistant-report.xml`

== 2.0.4

* Fixed an NPE if the goal `jqassistant:report` has been used from the command line

== 2.0.3

* Fixed issues regarding outdated Google Guice/Guava libraries provided by the jQAssistant Maven plugin (upgraded dependency to Reporting API to 3.2.0 and explicitly managed used Google Guava version)

== 2.0.2

* Fixed a bug where setting the configuration option `jqassistant.scan.reset` to `false` still resetted the existing store
* Fixed issues when using plugins related to the TCCL not being able to find classes from plugins (e.g. APOC)

== 2.0.0

* The configuration section has been removed from pom.xml in favor of using the settings in `.jqassistant.yml` and according system properties or environment variables
* The execution directory of Maven is now used as project root by default (`jqassistant.use-execution-root-as-project-root=true`), i.e. the database will be created in the target directory and the rules will be looked up in the folder `jqassistant/` of the module where the `mvn` command is executed.
* Removed (undocumented) goal `export-database`


== 1.12.0

* Added initial support for externalized configuration based on YAML files, environment variables and system properties
* Add configuration option `continueOnFailure` for the `analyze` goal

== 1.9.0

* Added configuration setting `createReportArchive` to the analyze goal for creating a ZIP archive containing the generated reports
* Added store configuration options `encryption`, `trustStrategy` and `trustCertificate` to control encryption for bolt connections to a Neo4j database
* Fixed a race condition for Maven builds running in multiple threads (e.g. `-T4`)

== 1.8.0

* Added Asciidoc Report plugin to the jQA Maven plugin, i.e. it does no longer need to be added as explicit dependency
* Removed configuration options for APOC and Graph Algorithms.
These will be available as separate plugins, see https://github.com/jqassistant-contrib/jqassistant-apoc-plugin[APOC plugin] and https://github.com/jqassistant-contrib/jqassistant-graph-algorithms-plugin[Graph Algorithms plugin].
* Removed deprecated options `jqassistant.severity`, `jqassistant.failOnViolations`, `jqassistant.server.address` and `jqassistant.server.port`

== 1.7.0

* Added configuration `graphAlgorithmsEnabled` for embedded server and system property `jqassistant.embedded.graphAlgorithmsEnabled`

== 1.6.0

* Removed deprecated system property `jqassistant.server.address` and replaced it by `jqassistant.embedded.listen_address`
* Removed deprecated system property `jqassistant.server.port` and replaced it by `jqassistant.embedded.httpPort`

== 1.5.0

* Added a section `embedded` to the `store` configuration section allowing to configure the embedded Neo4j server (listen address, ports and APOC registration)
* Deprecated system property `jqassistant.server.address` and replaced it by `jqassistant.embedded.listen_address`
* Deprecated system property `jqassistant.server.port` and replaced it by `jqassistant.embedded.httpPort`
* Added system properties `jqassistant.embedded.boltPort` and `jqassistant.embedded.apocEnabled`
* Fixed a problem that parallel builds could not be executed for scan/analyze goals (due to conflicting use of BOLT port)
* Fixed a problem of skipped analysis due to wrong detection of last module in a reactor

== 1.4.0

* Maven plugin automatically selects Neo4j v2 or Neo4j v3 depending on the available Java runtime environment
* Users can now provide the severity for the configuration parameters
  `failOnSeverity`, `warnOnSeverity`, and `storeLifecycle`
  also in lower case letters.
* Users can now provide the severity for the configuration parameter
  `failOnSeverity` and `warnOnSeverity` also in lower case.
* The plugin for Maven now logs the severity of constraint violations
  which will cause the build to fail before the analysis will start.
  It also logs the severity of constraint violations which will
  cause warnings but without failing the build.
* Fixed a bug regarding wrong default values for `warnOnSeverity` and `failOnSeverity`

== 1.3.0

* Added initial support for remote Neo4j 3.x databases (embedded or using bolt protocol)
* Allow switching to Neo4j 3 using property `-Djqassistant.neo4jVersion=3` (experimental)
* Added 'store' configuration section providing configuration options for remote database instances
* Added 'rule' configuration section providing default severities for groups, concepts and constraints
* Deprecated configuration attributes `severity` and `failOnViolations` and replaced them with `warnOnSeverity` and `failOnSeverity`
* Fixed a problem where dependencies between types in different Maven modules have not been resolved

== 1.2.0

* Maven coordinates changed from `com.buschmais.jqassistant.scm:jqassistant-maven-plugin`
  to `com.buschmais.jqassistant:jqassistant-maven-plugin`.
* Added support for rule parameters.




