[[YAMLFileScanner]]
== Generic scanner for YAML files

Imports http://yaml.org/spec/1.1/[YAML 1.1] files in a generic representation
for jQAssistant.

Seen from a more formal perspective a YAML document is build by a tree of nodes.
Each node can have one of the following values as content: scalar value, sequence
or mapping. This plugin imports a YAML file in a simplified manner as simply
model of keys and values. See section <<yaml-examples>> for examples.

IMPORTANT: This YAML scanner supports not the full YAML 1.1 specification as is
is intended to help to scan and validate YAML configuration files with the
help of a simple graph model. If you need an better support for YAML files,
please report a feature request.

=== Activation of the plugin

The YAML scanner is **not activated by default** for the jQAssistant Plugin for Maven,
but for the commandline tool for jQAssistant. To activated for the jQAssistant for
Maven it must be added to the list of dependencies as shown below.

[source, xml]
----
<plugin>
    <groupId>com.buschmais.jqassistant.scm</groupId>
    <artifactId>jqassistant-maven-plugin</artifactId>
    <version>{projectVersion}</version>
    <dependencies>
        <dependency>
            <groupId>com.buschmais.jqassistant.plugin</groupId>
            <artifactId>jqassistant.plugin.yaml</artifactId>
            <version{projectVersion}</version>
        </dependency>
    </dependencies>
</plugin>
----

=== :File:YAML

A file with the file extension `.yaml` containing zero or more YAML documents.

.Relations of :File:Xml
[options="header"]
|====
| Name              | Target label(s)    | Cardinality    | Description
| CONTAINS_DOCUMENT | <<:Document:YAML>> | 0..n           | References a document in the file
|====

.Properties of :File:YAML
[options="header"]
|====
| Name    | Description
| valid   | Property to indicate if the documents of this file have been parsed
            successfully or not. If the YAML scanner was able to parse all
            documents, this property is _true_. Otherwise it is _false_.
            This property can be used to check if all of your YAML files
            could have been parsed or not.
|====

An non-parsable file with YAML documents will not have any outgoing relationships
to any dependent <<:Document:YAML,YAML documents>>. Please consider this aspect
when writing your queries.

[[:Document:YAML]]
=== :Document:YAML

.Relations of :Document:YAML
[options="header"]
|===
| Name           | Target label(s)  | Cardinality | Description
| CONTAINS_VALUE | <<:Key:YAML>>    | 0..n        | References a key in the containing document
| CONTAINS_KEY   | <<:Value:YAML>>  | 0..n        | References a value in the containing document
|===

[[:Key:YAML]]
=== :Key:YAML

.Properties of :Key:YAML
[options="header"]
|====
| Name   | Description
| name   | The name of the key
| fqn    | The full qualified name of the key. It is build by joining all parent keys and the
           name of the current key with a dot as delimiter
|====


.Relations of :Key:YAML
|===
| Name           | Target label(s)  | Cardinality | Description
| CONTAINS_KEY   | <<:Key:YAML>>    | 0..n        | References a child key of the containing key
| CONTAINS_VALUE | <<:Value:YAML>>  | 0..n        | References a value assigned to the key
|===


[[:Value:YAML]]
=== :Value:YAML

Nodes tagged with `:Value:YAML` represents YAML scalars assigned to a <<:Key:YAML>>.

.Properties of :Value:YAML
|===
| Name  | Description
| value | The value itself.
|===

.Relations of :Value:YAML
|===
| Name           | Target label(s) | Cardinality | Description
| CONTAINS_VALUE | <<:Value:YAML>> | 0..n        | References a child value assigned to this value
|===

[[yaml-examples]]
=== Examples

Not written yet.




