==== Custom Rule Extension
A custom rule extension can be implemented to make user defined jQAssistant rules available for SonarQube. It is a
Maven project which declares packaging 'sonar-plugin':

[source,xml]
.pom.xml
----
<project ...>
...

include::{docRoot}/jqassistant.examples.sonar.ruleextension/src/pom.xml[lines=11..60,indent=0]

...
</project>
----

Notes on the sonar plugin configuration:

- 'basePlugin' must be set to 'jQAssistant' to indicate which plugin shall be extended.
- The implementation of 'pluginClass' (i.e. 'MyJQAssistantExtension') returns an empty list of extensions. It must be specified as this is required by SonarQube.

[source,java]
.MyJQAssistantExtension.java
----
include::{docRoot}/jqassistant.examples.sonar.ruleextension/src/src/main/java/com/buschmais/jqassistant/examples/sonar/ruleextension/MyJQAssistantExtension.java[]
----

The rules itself are packaged according to the following structure:

[source,xml]
./META-INF/jqassistant-plugin.xml
----
include::{docRoot}/jqassistant.examples.sonar.ruleextension/src/src/main/resources/META-INF/jqassistant-plugin.xml[]
----

* example.xml specifies the path to a jQAssistant rule file relative to /META-INF/jqassistant-rules

[source,xml]
./META-INF/jqassistant-rules/example.xml
----
include::{docRoot}/jqassistant.examples.sonar.ruleextension/src/src/main/resources/META-INF/jqassistant-rules/example.xml[]
----

The created JAR archive and the jQAssistant must be copied to the folder 'extensions/plugins' of the SonarQube installation. The defined
rules will be visible in the repository "jQAssistant".
