@startuml

class Class
class Method
class Field

interface Bound
interface TypeVariable {
  name
}
interface GenericArrayType
interface ParameterizedType
interface WildcardType

interface GenericDeclaration

Bound <|.. Class
Bound <|.. GenericArrayType
Bound <|.. ParameterizedType
Bound <|.. WildcardType
Bound <|.. TypeVariable

GenericDeclaration <|.. Class
GenericDeclaration <|.. Method

GenericArrayType   -- Bound : componentType

ParameterizedType  -- "0..*" Bound : actualTypeArguments
ParameterizedType  -- "1"    Bound : rawType
ParameterizedType  -- "1"    Bound : ownerType

WildcardType -- "0..*" Bound : upperBounds
WildcardType -- "0..*" Bound : lowerBounds

TypeVariable       -- "0..*" Bound            : upperBounds

GenericDeclaration -- "0..*" TypeVariable : typeParameters

Method -- "1" Bound : genericReturnType
Method -- "0..*" Bound : genericParameterTypes
Method -- "1" Bound : genericExceptionTypes

Field -- "1" Bound : genericType

@enduml

