==== Custom Report Plugin

A custom report plugin may be implemented to create custom representations of analysis results. Such a plugin must be
provided as an artifact which contains a Java class and a plugin descriptor. Therefore a project is required which
declares the required dependencies:

[source,xml]
.pom.xml
----
include::{docRoot}/jqassistant.examples.plugins.report/src/pom.xml[tags=dependencies,indent=0]
----

The artifact 'jqassistant.core.report' provides the report plugin API, 'jqassistant.plugin.java' provides interfaces representing Java types
which might be used by the plugin implementation:

[source,java]
.com.buschmais.jqassistant.examples.plugins.report.CustomReportPlugin
----
include::{docRoot}/jqassistant.examples.plugins.report/src/src/main/java/com/buschmais/jqassistant/examples/plugins/report/CustomReportPlugin.java[tags=class]
----

The plugin implementation must be declared in the jQAssistant plugin descriptor:

[source,xml]
./META-INF/jqassistant-plugin.xml
----
include::{docRoot}/jqassistant.examples.plugins.report/src/src/main/resources/META-INF/jqassistant-plugin.xml[]
----

The plugin is automatically loaded by the analyzer if it can be found on the classpath, e.g. by adding it as dependency to the maven plugin. The report
plugin will be used automatically or may be explicitly selected per rule by its id (i.e. "custom").

