== GraphML Report

This plugin generates graphml xml files for result data of concepts. Those files can be used with several graph rendering
and analytics tools like http://www.yworks.com/en/products/yfiles/yed/[yEd] and http://gephi.org[Gephi].

By default all concepts ending in `.graphml` will be rendered (e.g. "module:modules.graphml").

=== Configuration

.Configuration properties
[options="header"]
|====
| Property     			        | Description														                                 | Default
| graphml.report.conceptPattern | Regular expression that describes the concept ids to use for rendering the result as GraphML file. | .*\.graphml$
| graphml.report.directory      | The directory where the .graphml files will be created                                             | jqassistant/report
| graphml.report.decorator      | Specify the name of a class implementing the 'GraphMLDecorator' interface for layouting a graph    | YedGraphMLDecorator
|====

=== Example

The following concept will return package dependencies (as provided by the concept <<dependency:Package>>) as GraphML document:

[source,xml]
.reports.xml
----
<jqa:jqassistant-rules xmlns:jqa="http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0">

    <concept id="report:PackageDependencies.graphml">
        <requiresConcept refId="dependency:Package" />
        <description>Reports all package dependencies.</description>
        <cypher><![CDATA[
            MATCH
              (p1:Package)-[d:DEPENDS_ON]->(p2:Package)
            RETURN
              p1, d, p2
        ]]></cypher>
    </concept>

</jqa:jqassistant-rules>
----

The plugin also supports virtual relations, i.e. which are constructed in the return clause of the query. 
A part of the return clause constructs a JSON-Object with several properties: 

role:: to identify the type of virtual element (value: relationship)
type:: relationship type
startNode:: the start node of the relationship
endNode:: the end node of the relationship

The following example virtually propagates the dependencies of Java types to the package level without creating a relationship in the
store:

[source,xml]
.reports.xml
----
<jqa:jqassistant-rules xmlns:jqa="http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0">

    <concept id="report:VirtualPackageDependencies.graphml">
        <description>Reports all package dependencies.</description>
        <cypher><![CDATA[
            MATCH
              (p1:Package)-[:CONTAINS]->(t1:Type),
              (p2:Package)-[:CONTAINS]->(t2:Type),
              (t1)-[:DEPENDS_ON]->(t2)
            RETURN
              p1,
              {
                role: "relationship",
                type: "DEPENDS_ON",
                startNode: p1,
                endNode: p2
              },
              p2
        ]]></cypher>
    </concept>

</jqa:jqassistant-rules>
----

Virtual nodes will be provided in the same way like virtual relationships. These are the properties to use in the JSON-Object:

role:: to identify the type of virtual element (value: node)
properties:: node properties
labels:: a list of labels for this node

The following example virtually aggregates some data without creating a node in the store:

[source,xml]
.reports.xml
----
<jqa:jqassistant-rules xmlns:jqa="http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0">

    <concept id="report:VirtualDataNode.graphml">
        <description>Aggregates data in a virtual node.</description>
        <cypher><![CDATA[
            MATCH
              (m:Method)
            RETURN
              {
                role: "node",
                properties: {totalCyclomaticComplexity : sum(m.cyclomaticComplexity)},
                labels: ["Metrics", "CyclomaticComplexity"]
              }
        ]]></cypher>
    </concept>

</jqa:jqassistant-rules>
----

To get a better structured GraphML-File subgraphs can be generated. With this pattern it is possible to drill down in the graph. These are the properties to use in the JSON-Object:

role:: to identify the type of virtual element (value: graph)
parent:: subgraphs must be nested in a parent node
nodes:: all nodes that will be included in the subgraph
relationships:: a list of relationships for the nodes. The relationships will be drawn if start- and end-node are part of the GraphML-file.

The following example creates a virtual subgraph:

[source,xml]
.reports.xml
----
<jqa:jqassistant-rules xmlns:jqa="http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0">

    <concept id="report:Subgraph.graphml">
        <description>Creates a Subgraph for a better overview.</description>
        <cypher><![CDATA[
            MATCH
              (t:Class)-[:DECLARES]->(m:Method)
            OPTIONAL MATCH
              (m)-[i:INVOKES]->(:Method)
            RETURN
              {
                role: "graph",
                parent: t,
                nodes: collect(m),
                relationships: collect(i)  //<1>
              } as subgraph
		]]></cypher>
    </concept>

</jqa:jqassistant-rules>
----
<1> The relationships can be used overall subgraphs