== 1.0.0-RC2

=== Core

==== Store
- Upgraded to Neo4j 2.2.0

==== Analysis
- added exlicit verification strategies for executable rules
- clarified behavor of concepts and constraints regarding to configured severities

=== Maven
- Fixed problems of report goal in site lifecycle
- Allow Maven plugin to be configured as build extension

=== Plugins

==== Java
- Scanner adds a property "md5" containing the hash sum to each scanned class.
- Scanner adds a property "byteCodeVersion" to each scanned class and "cyclomaticComplexity" to each scanned method
- Added a new concept "java:JavaVersion": Set a human readable property "javaVersion" on a class file based on its byte code version
- Referenced types are now also resolved using the transitive dependencies of the containing artifact

==== RDBMS
- Database schemas may be scanned from the command line without creating a specific property file

==== Plugin API
- ReportPlugin#setResult now takes a 'Result<? extends ExecutableRule>' as parameter (instead of 'Result<? extends Rule>')

==== XML
- Prevent online schema lookups for DTDs while parsing documents

