== 1.0.0-RC

=== Core

==== Rules
- added support for rules as script (e.g. Ruby, Groovy, JavaScript etc.) using the Java Scripting API

=== Maven plugin
- minimum requirement has been changed to Apache Maven 3.2.x
- added support for scopes: scope element in scanIncludes and a new goal available-scopes

=== Command line
- added command line support for scopes, e.g. scan -f java:classpath::/My/ClassPath/

=== Plugins

==== JUnit
- renamed JUnit4 plugin to JUnit as it also contains rules for JUnit3

==== TestNG
- added TestNG plugin containing concepts

==== RDBMS
- added RDBMS plugin containing a scanner to import schema metadata for relational databases

==== Facelet
- added facelet plugin providing a scanner for JSF 2.x XHTML based views

==== Java EE 6
- added scanners for EAR archives and application.xml descriptors
- added scanners for WAR archives and web.xml descriptors

==== XML
- added XML plugin containing a generic scanner for XML files

==== Maven Repository
- added Maven 2 Repository plugin containing a scanner for incremental scans of remote repositories

=== Plugin API
- added annotation @Requires for scanner plugins to build dependency chains
- added mandatory "name" attribute to jqassistant-plugin element of jqassistant-plugin.xml descriptors
- moved file related model classes from package 'c.b.j.core.store.api.model' to 'c.b.j.plugin.common.api.model'