== 1.1.0

=== Core
- Groups may be defined in AsciiDoc documents
- Make sure that ids used for concepts, constraints or groups are unique nevertheless if they have been defined in XML or AsciiDoc documents
- Upgraded to Neo4j 2.2.5
- For plugin developers: marked the descriptor _com.buschmais.jqassistant.core.store.api.model.NamedDescriptor_ as deprecated
  and replaced it by _com.buschmais.jqassistant.plugin.common.api.model.NamedDescriptor_, plugin implementations should use this type

=== Maven
- Reset store (i.e. database) while building the root module of a project (was: execution root of Maven reactor)
- Added serverAddress and serverPort parameters to jqassistant:server goal

=== CLI
- Added serverAddress and serverPort parameters to server task
- Fixed a problem that .adoc files containing rules have not been evaluated

=== Plugins

==== GraphML
- Added plugin which provides a GraphML export for the results of executed concepts, includes support for virtual elements (sub graphs, nodes, relationships)

==== Maven Repository
- Resolve the POM model to provide full information about dependencies, plugins, etc.
- Added properties for filtering artifacts while scanning
- Added a relation CONTAINS_POM from the repository to each contained POM model (:Maven:Pom:Xml)

==== Tycho
- Upgraded scanner plugin to to Tycho 0.23.1 to fix compatibility issues

==== YAML
- Added plugin which provides a scanner for YAML files

==== JUnit
- Fixed an exception which has been logged during Maven build while parsing surefire and failsafe reports

=== Documentation
- Added an example to demonstrate using rules in AsciiDoc documents
