== 1.1.4

=== Core

- Upgraded to Neo4j 2.3.7
- Added support for array properties in reports (e.g. HTML)

=== Plugins

==== Common

- Added support for using file patterns (file.include and file.exclude) for scanner plugins.

==== Java

- Added attribute "weight" to DEPENDS_ON relations between types
- Fixed a bug where redundant and cyclic DECLARES relations have been created between outer and their inner classes
- Annotation nodes are now also labeled with "Java"
- Fixed a bug with where type resolution created multiple nodes when scanning directories with java:classpath scope

==== JavaEE6

- Fixed a bug where 'Package' label has not been added to for packages located in the WEB-INF/classes folder of a WAR file
- Fixed a bug where scanning a WAR file create duplicate nodes for types located in /WEB-INF/classes folder

==== GraphML

- Fixed a bug where sub graphs have not been evaluated properly

==== XML
- Added file pattern support (xml.file.include and xml.file.exclude) for specifying XML documents without a native
scanner plugin.
