"%test-store":
  jqassistant:
    store:
      uri: "file://${project.build.directory}/test-store"
"%activeByDefaultProfile":
  jqassistant:
    store:
      uri: "file://${project.build.directory}/active-by-default-story"
"%userProfile":
  jqassistant:
    store:
      uri: "file://${project.build.directory}/user-store"


