"%test-store":
  jqassistant:
    store:
      uri: "file://${project.build.directory}/test-store"
"%activeByDefault":
  jqassistant:
    store:
      uri: "file://${project.build.directory}/active-by-default-store"


