== Command Line

Shell scripts are provided for executing jQAssistant from the command line of Microsoft Windows(R) or Unix compatible
systems. They are located in the bin/ directory of the distribution:

* jqassistant.cmd
* jqassistant.sh

The command line accepts tasks and their specific options:

[source]
----
jqassistant.sh <task1> <task2> <task3> -<option1> -<option2>
----

The following example will scan the content of the directories classes/ and test-classes/:

[source]
----
jqassistant.sh scan -f classes,test-classes
----

=== Tasks

* <<cli:scan>>
* <<cli:available-scopes>>
* <<cli:analyze>>
* <<cli:available-rules>>
* <<cli:effective-rules>>
* <<cli:report>>
* <<cli:server>>

[[cli:scan]]
==== scan
===== Description
Scans files or directories and stores the gathered information in database. Files or URLs are accepted and may be
specified further by scopes, e.g.

[source]
----
jqassistant.sh scan -f lib/,plugins/
jqassistant.sh scan -f java:classpath::classes/
jqassistant.sh scan -u http://host/artifact.jar
jqassistant.sh scan -u http://user:secret@host/artifact.jar
jqassistant.sh scan -u maven:repository::http://my.maven.repository
----

===== Options
* <<cli:storeDirectory>>

* -f [<scope>::]<file1>,[<scope>::]<file2> or --files [<scope>::]<file1>,[<scope>::]<file2>
** specifies a list of files or directories to scan
** a scope may be used as prefix for each file argument

* -u [<scope>::]<url1>,[<scope>::]<url2> or --urls [<scope>::]<url1>,[<scope>::]<url2>
** specifies a list of URLs to scan
** a scope may be used as prefix for each url argument

* -reset
** reset the database before scanning

* -continueOnError
** continue scanning even if a plugin fails with an unrecoverable error

NOTE: Using -continueOnError might create inconsistent data. Any reported errors should be reported to the plugin developer.

[[cli:available-scopes]]
==== available-scopes
===== Description
List all available scopes which may be specified for scanning.

[[cli:analyze]]
==== analyze
===== Description
Executes an analysis.

===== Options
* <<cli:concepts>>
* <<cli:constraints>>
* <<cli:groups>>
* <<cli:storeDirectory>>
* <<cli:ruleDirectory>>
* <<cli:rulesUrl>>
* <<cli:reportDirectory>>

* -severity <severity>
** specifies the severity of a problem for the analysis to fail. The program will return with exit code 2.
** values: 'info', 'minor', 'major', 'critical' or 'blocker'
** default: 'minor'
* -executeAppliedConcepts
** Execute concepts which have already been applied before. The default is 'false' to save time on repeated runs of "analyze" on the
   same data. Setting this flag to 'true' is useful for creating and trying out new concepts.

[[cli:available-rules]]
==== available-rules
===== Description
List all available rules.

===== Options
* <<cli:ruleDirectory>>
* <<cli:rulesUrl>>

[[cli:effective-rules]]
==== effective-rules
===== Description
List the rules which would be executed for an analysis and the given concepts, constraints or groups.

===== Options
* <<cli:concepts>>
* <<cli:constraints>>
* <<cli:groups>>
* <<cli:ruleDirectory>>
* <<cli:rulesUrl>>

[[cli:report]]
==== report
===== Description
Transforms an XML report into HTML.

===== Options
* <<cli:reportDirectory>>

[[cli:server]]
==== server
===== Description
Starts the integrated Neo4j web server.

* -serverAddress <address>
** specifies the binding address for the server (default: localhost)
* -serverPort <port>
** specifies the binding port for the server (default: 7474)
* -daemon
** terminate the server using <Ctrl-c> instead of waiting for standard input (allows to run the server on a machine as a background process / service)

===== Options
* <<cli:storeDirectory>>

==== Common options

[[cli:storeDirectory]]
===== -s, --storeDirectory <directory>
* specifies the location of the database to use
* default: './jqassistant/store'

[[cli:concepts]]
===== -concepts <concept1>,<concept2>
* specifies the ids of the concepts to be applied

[[cli:constraints]]
===== -constraints <constraint1>,<constraint2>
* specifies the ids of the constraints to be validated

[[cli:groups]]
===== -groups <group1>,<group2>
* specifies the ids of the groups to be executed
* default: 'default'

[[cli:ruleDirectory]]
===== -r, --ruleDirectory <directory>
* specifies the directory where rule files are located
* default: './jqassistant/rules'

[[cli:rulesUrl]]
===== -rulesUrl <url>
* specifies the URL of a file containing rules
* this option is exclusive, i.e. it will disable loading rules from plugins or rule directories

[[cli:reportDirectory]]
===== -reportDirectory
* specifies the directory where reports (XML, HTML) will be stored
* default: './jqassistant/report'
