== Quickstart

=== Command Line

==== Requirements
- Java Development Kit 8 or later
- the environment variable JQASSISTANT_OPTS should be set to adjust memory settings

[source]
.Windows
----
set JQASSISTANT_OPTS=-Xmx1024M
----

[source]
.Linux
----
export JQASSISTANT_OPTS=-Xmx1024M
----

==== Installation

* Download and unpack the distribution, a directory
  `jqassistant-commandline-neo4jvx-_version_` will be created.

==== Scan

[source]
.Windows
----
bin\jqassistant.cmd scan -f lib
----

[source]
.Linux
----
bin/jqassistant.sh scan -f lib
----

* The JAR files contained in the lib/ folder will be scanned.

==== Explore

[source]
.Windows
----
bin\jqassistant.cmd server
----

[source]
.Linux
----
bin/jqassistant.sh server
----

* Open a browser and navigate to http://localhost:7474[http://localhost:7474]
* Enter the following query in the top level area and hit Ctrl-Enter:

[source]
----
MATCH
  (a:Artifact)-[:CONTAINS]->(t:Type)-[:DECLARES]->(m:Method)
RETURN
  a.fileName as Artifact, t.fqn AS Type, count(t) AS DeclaredMethods
ORDER BY
  DeclaredMethods DESC
LIMIT 20
----

=== Maven

==== Requirements
- Maven 3.5 or later
- Java Development Kit 8 or later
- the environment variable MAVEN_OPTS must be set to adjust memory settings

[source]
.Windows
----
set MAVEN_OPTS=-Xmx1024M
----

[source]
.Linux
----
export MAVEN_OPTS=-Xmx1024M
----

==== Add the plugin

Add the following lines to the parent pom.xml file of your project:

[source,xml]
----
<properties>
  <!-- Define your desired jQAssistant version here -->
  <jqassistant.version>...</jqassistant.version>
</properties>
<build>
    <plugins>
        <plugin>
            <groupId>com.buschmais.jqassistant</groupId>
            <artifactId>jqassistant-maven-plugin</artifactId>
            <version>${jqassistant.version}</version>
            <executions>
                <execution>
                    <goals>
                        <goal>scan</goal>
                        <goal>analyze</goal>
                    </goals>
                    <configuration>
                        <failOnSeverity>MAJOR</failOnSeverity>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
----

==== Add a rule

Within your parent module create a directory `jqassistant` and a file `my-rules.adoc`:

[source,xml]
.jqassistant/my-rules.adoc
....
= My Project

// Include a summary of all executed rules and their status
include::jQA:Summary[]

[[default]]
[role=group,includesConstraints="my-rules:*"]
== Default Rules

[[my-rules:TestClassName]]
[source,cypher,role=constraint,requiresConcepts="junit4:TestClass"]
----
MATCH
    (t:Junit4:Test:Class)
WHERE NOT
    t.name ends with "Test"
RETURN
    t AS InvalidTestClass
----

== Imported Rules

// Include specific rules that have been executed and their results.
include::jQA:Rules[concepts="junit*:*"]
....

==== Run the build

Execute the following command from your parent module:

[source]
----
mvn install
----

The build will fail with the rule's message if it is violated.

The HTML report generated from the Asciidoc file including all results is available from `target/jqassistant/report/asciidoc/index.html`.

==== Explore your application

jQAssistant comes with an integrated Neo4j server, you can run it using

[source]
----
mvn jqassistant:server
----

* Open a browser and navigate to http://localhost:7474[http://localhost:7474]
* Enter the follwoing query in the top level area and hit Ctrl-Enter:

[source]
----
MATCH
  (t:Type)-[:DECLARES]->(m:Method)
RETURN
  t.fqn AS Type, count(t) AS DeclaredMethods
ORDER BY
  DeclaredMethods DESC
LIMIT 20
----
