== Quickstart

=== Command Line

==== Requirements

- Java Development Kit 11 or 17
+
NOTE: Java 21 is currently not supported if the embedded Neo4j database is used.

- The following JVM parameters are required if `Java 17` is used as runtime environment:
+
.Windows
----
set JQASSISTANT_OPTS=--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED
----
+
.Linux
----
export JQASSISTANT_OPTS=--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED
----

==== Installation

* The latest command line distribution is available on https://search.maven.org/search?q=a:jqassistant-commandline-distribution[Maven Central], select `bin.zip` from the `Download` menu.
* Download and unpack the distribution, a directory
  `jqassistant-commandline-distribution-_version_` will be created.

==== Scan

[source]
.Windows
----
bin\jqassistant.cmd scan -f lib
----

[source]
.Linux
----
bin/jqassistant.sh scan -f lib
----

* The JAR files contained in the lib/ folder will be scanned.

==== Explore

[source]
.Windows
----
bin\jqassistant.cmd server
----

[source]
.Linux
----
bin/jqassistant.sh server
----

* Open a browser and navigate to http://localhost:7474[http://localhost:7474]
* Enter the following query in the top level area and hit Ctrl-Enter:

[source]
----
MATCH
  (a:Artifact)-[:CONTAINS]->(t:Type)-[:DECLARES]->(m:Method)
RETURN
  a.fileName as Artifact, t.fqn AS Type, count(t) AS DeclaredMethods
ORDER BY
  DeclaredMethods DESC
LIMIT 20
----

=== Maven

==== Requirements

- Maven 3.5 or later
- Java Development Kit 11 or 17
+
NOTE: Java 21 is currently not supported if the embedded Neo4j database is used.

- The following JVM parameters are required if `Java 17` is used as runtime environment:
+
.Windows
----
set MAVEN_OPTS=--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED
----
+
.Linux
----
export MAVEN_OPTS=--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED
----
+
An alternative option is to place these settings into a file `.mvn/jvm.config` in the root Maven module:
+
[source]
..mvn/jvm.config
----
--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED
----


==== Add the plugin

Add the following lines to the parent pom.xml file of your project:

[source,xml,subs=attributes+]
----
<project>
    <properties>
        <!-- Define your desired jQAssistant version here -->
        <jqassistant.version>{projectVersion}</jqassistant.version>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>com.buschmais.jqassistant</groupId>
                <artifactId>jqassistant-maven-plugin</artifactId>
                <version>${jqassistant.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>scan</goal>
                            <goal>analyze</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
----

==== Add a rule

Within your parent module create a directory `jqassistant` and a file `my-rules.adoc`:

[source,xml]
.jqassistant/my-rules.adoc
....
= My Project

// Include a summary of all executed rules and their status
include::jQA:Summary[]

[[default]]
[role=group,includesConstraints="my-rules:*"]
== Default Rules

[[my-rules:TestClassName]]
[source,cypher,role=constraint,requiresConcepts="junit4:TestClass"]
----
MATCH
    (t:Junit4:Test:Class)
WHERE NOT
    t.name ends with "Test"
RETURN
    t AS InvalidTestClass
----

== Imported Rules

// Include specific rules that have been executed and their results.
include::jQA:Rules[concepts="junit*:*"]
....

==== Run the build

Execute the following command from your parent module:

[source]
----
mvn install
----

The build will fail with the rule's message if it is violated.

The HTML report generated from the Asciidoc file including all results is available from `target/jqassistant/report/asciidoc/index.html`.

==== Explore your application

jQAssistant comes with an integrated Neo4j server, you can run it using

[source]
----
mvn jqassistant:server
----

* Open a browser and navigate to http://localhost:7474[http://localhost:7474]
* Enter the follwoing query in the top level area and hit Ctrl-Enter:

[source]
----
MATCH
  (t:Type)-[:DECLARES]->(m:Method)
RETURN
  t.fqn AS Type, count(t) AS DeclaredMethods
ORDER BY
  DeclaredMethods DESC
LIMIT 20
----
