== Introduction

This chapter provides an introduction to the concepts of jQAssistant.

=== How it works

The basic idea behind jQAssistant is to integrate the following steps into the build process of a software system:

1. Scan the generated artifacts and store structural information about them into a database
2. Analyze the structures using _rules_ which are represented by queries
3. Report violations  

jQAssistant itself is a plugin based framework. It comes with a pre-defined set of plugins containing scanners, rules and reports but can be easily extended by
custom rules or implementations.

As database an embedded instance of Neo4j Community Edition is managed and used by jQAssistant. This means that no setup or configuration of a dedicated server
is required. Neo4j has been chosen because:

- it is a mature open source graph database
- it allows easy modelling of structural elements of a software and their relations
- it comes with a very expressive and easy to learn query language (Cypher)

=== Rules

Rules are expressed as Cypher queries and are specified either in XML or AsciiDoc files.

==== XML example

[source,xml]
.my-rules.xml
----
<jqa:jqassistant-rules xmlns:jqa="http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0">

    <group id="default">
        <includeConstraint refId="my-rules:MyConstraint"/>
    </group>

    <constraint id="my-rules:MyConcept">
        <description>A human readable description of the concept.</description>
        <cypher><![CDATA[
            MATCH
              ...
            WHERE
              ...
            SET
              ...
            CREATE
              ...
            RETURN
              ...
        ]]></cypher>
    </constraint>

    <constraint id="my-rules:MyConstraint">
        <requiresConcept refId="my-rules:MyConcept" />
        <description>A human readable description of the constraint.</description>
        <cypher><![CDATA[
            MATCH
                ...
            WHERE
                ...
            RETURN
                ...
        ]]></cypher>
    </constraint>

</jqa:jqassistant-rules>
----

==== AsciiDoc example

[source,asciidoc]
.my-rules.adoc
....

[[my-rules:MyConcept]]
.A human readable description of the concept.
[source,cypher,role=concept]
----
MATCH
  ...
WHERE
  ...
SET
  ...
CREATE
  ...
RETURN
  ...
----

[[my-rules:MyConstraint]]
.A human readable description of the constraint.
[source,cypher,role=constraint,depends="my-rules:MyConcept"]
----
MATCH
  ...
WHERE
  ...
RETURN
  ...
----

....

Each rule comes with an unique id (e.g. "my-rules:MyConstraint") which can be referenced by other rules. jQAssistant will take care about executing the rules in
the correct order. Furthermore a human readable description shall help developers to understand the rationale behind them.

A rule can optionally define the _severity_ level. jQAssistant allows to break the build if there are violations in the configured severity level (or higher).
For example, if the severity is set to critical, and if there are violated constraints with blocker and/or critical severity; the build will break. 
This feature allows projects to pay down their technical debt in an iterative manner.

Following severity levels are supported:

- info
- minor
- major
- critical
- blocker

==== Groups
A group is a set of rules that shall be executed together. This allows to adjust analysis depth for different types of builds, e.g. a Continuous Integration
build (CI) can be configured to only execute rules with low costs (i.e. execution times) whereas a report build is allowed to run for a longer time with more
expensive checks.

==== Concepts
The information created by the scanner represents the structure of a software project on a raw level. _Concept_ rules allow enriching the database with higher
level information to ease the process of writing queries that check for violations (i.e. constraints) . This typically means adding labels, properties or
relations.

jQAssistant comes with language and framework plugins which include general technical concepts, e.g.

- "jpa2:Entity" provided by the JPA2 plugin adds a label "Entity" to a node if it represents a class which is annotated by "@javax.persistence.Entity".
- "java:MethodOverrides" provided by the Java plugin adds a relation "OVERRIDES" between a method of a sub class to the super class methods it overrides.

It is recommended to use concepts to enrich the database with information which is specific for the concrete project, e.g. labels can be added to

- package nodes representing modules of the application ("Module")
- package nodes that represent technical layers ("UI", "EJB")
- class nodes representing elements with a specific role ("Controller", "Model")

*NOTE* Even if the primary intention of a concept is to enrich data it still must provide a return clause. If a concept returns an empty result a warning will
be generated by jQAssistant. The rationale is that in such case the concept does not match the structure of the application and other rules which depend on it
will probably not work as expected. The return clause of the concept shall preferably return a node/relation itself instead of an attribute of it. 
Similarly, return clauses with only count of matching nodes shall be avoided. With this, XML and HTML reports can provide additional information about the concept.

==== Constraints
A _Constraint_ is a query which detects violations, e.g.

- classes with specific roles (e.g. entity, controller, etc.) that are either located in the wrong packages or have names that do not fit defined conventions
- invocations of methods which are deprecated and/or forbidden (e.g. constructors of java.util.Date)
- dependencies to other modules which are not allowed

A constraint can depend on one or more concepts and usually is referenced by one or more groups.

*NOTE* If a constraint returns a result jQAssistant will report an error including the provided description and information about the returned elements. This
information shall help the developer to understand and fix the problem.

