== Quickstart

=== Command Line

==== Installation

* Download and unpack the distribution, a directory "{projectArtifactId}-{projectVersion}" will be created.

==== Scan

[source]
.Windows
----
bin/jqassistant.cmd scan -f lib
----

[source]
.Linux
----
bin/jqassistant.sh scan -f lib
----

* The JAR files contained in the lib/ folder will be scanned.

==== Explore

[source]
.Windows
----
bin/jqassistant.cmd server
----

[source]
.Linux
----
bin/jqassistant.sh server
----

* Open a browser and navigate to http://localhost:7474[http://localhost:7474]
* Enter the follwoing query in the top level area and hit Ctrl-Enter:

[source]
----
MATCH
  (t:Type)-[:DECLARES]->(m:Method)
RETURN
  t.fqn AS Type, count(t) AS DeclaredMethods
ORDER BY
  DeclaredMethods DESC
LIMIT 20
----

=== Maven

==== Add the plugin

Add the following lines to the parent pom.xml file of your project:

[source,xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>com.buschmais.jqassistant.scm</groupId>
            <artifactId>jqassistant-maven-plugin</artifactId>
            <executions>
                <execution>
                    <id>scan</id>
                    <goals>
                        <goal>scan</goal>
                    </goals>
                </execution>
                <execution>
                    <id>analyze</id>
                    <goals>
                        <goal>analyze</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>

<reporting>
    <plugins>
        <plugin>
            <groupId>com.buschmais.jqassistant.scm</groupId>
            <artifactId>jqassistant-maven-plugin</artifactId>
            <reportSets>
                <reportSet>
                    <reports>
                        <report>report</report>
                    </reports>
                </reportSet>
            </reportSets>
        </plugin>
    </plugins>
</reporting>
----

==== Add a rule

Within your parent module create a directory "jqassistant" and a rules file in it:

[source,xml]
----
<jqa:jqassistant-rules xmlns:jqa="http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0">

    <group id="default">
        <includeConstraint refId="my-rules:TestClassName" />
    </group>

    <constraint id="my-rules:TestClassName">
        <requiresConcept refId="junit4:TestClass" />
        <description>All JUnit test classes must have a name with suffix "Test".</description>
        <cypher><![CDATA[
            MATCH
                (t:Junit4:Test:Class)
            WHERE NOT
                t.name =~ ".*Test"
            RETURN
                t AS InvalidTestClass
        ]]></cypher>
    </constraint>

</jqa:jqassistant-rules>

----

==== Run the build

Execute the following command from your parent module:

[source]
----
mvn install
----

The build will fail with the message specified by your rule if it is violated. If everything is fine you can also create a report as part of your Maven site:

[source]
----
mvn site
----

==== Explore your application

jQAssistant comes with an integrated Neo4j server, you can run it using

[source]
----
mvn jqassistant:server
----

* Open a browser and navigate to http://localhost:7474[http://localhost:7474]
* Enter the follwoing query in the top level area and hit Ctrl-Enter:

[source]
----
MATCH
  (t:Type)-[:DECLARES]->(m:Method)
RETURN
  t.fqn AS Type, count(t) AS DeclaredMethods
ORDER BY
  DeclaredMethods DESC
LIMIT 20
----
