==== Scripting

Demonstrates a constraint implemented using JavaScript.

[source,xml]
.jqassistant/default.xml
----
include::{docRoot}/jqassistant.examples.rules.scripting/src/jqassistant/default.xml[]
----

Other scripting languages may be used as well if they integrate with the Java Scripting API (JSR-223), e.g. Groovy or JRuby.
The corresponding libraries must be available on the classpath of jQAssistant, e.g. by adding a dependency to the Maven plugin:

[source,xml]
.pom.xml
----
include::{docRoot}/jqassistant.examples.rules.scripting/src/pom.xml[lines=12..32,indent=0]
----

The following global variables are provided to the script:

store::
    The store instance of type _com.buschmais.jqassistant.core.store.api.Store_ which provides access to the graph database.
rule::
    The rule to be executed, i.e. a an instance of _com.buschmais.jqassistant.core.analysis.api.rule.ExecutableRule_.
severity::
    The effective severity.

The script must return a result which is structured like a database result consisting of rows each represented by a
map of named columns and their values. Therefore an instance of _com.buschmais.jqassistant.core.analysis.api.Result_ must
be created which takes the following constructor arguments:

rule::
    The rule as provided to the script.
severity::
    The severity to report, a value of the enum type _com.buschmais.jqassistant.core.analysis.api.rule.Severity_.
columnNames::
    A _java.util.List_ containing strings representing the column names.
rows::
    A _java.util.List_ containing instances of _java.util.Map_ where each map represents a single row consisting of the
    column name as key and a corresponding value.

TIP: The rule can also be specified in an AsciiDoc document:

[source,asciidoc]
.jqassistant/default.adoc
....
include::{docRoot}/jqassistant.examples.rules.scripting/src/jqassistant/default.adoc[]
....