
= Maven 3 Plugin

== 2.3.0

* Added missing classifier `tests` to test artifacts created by the Maven project scanner
* Ensure that the property `fileName` is set for `:Maven:Project` nodes that represent local (i.e. scanned) Maven projects

== 1.12.0

* Removed deprecated graph model `(:Pom)-[:DECLARES_DEPENDENCY]\->(:Maven:Artifact)`, it has been replaced by a model supporting exclusions (see deprecation notice in 1.9.0)

== 1.10.1

* Fixed a problem where scanning dependencies either skipped artifacts (if specified in dependency management) or scanned them multiple times

== 1.9.0

* Deprecated graph model `(:Pom)-[:DECLARES_DEPENDENCY]\->(:Maven:Artifact)`, it has been replaced by a model supporting exclusions:

  (:Pom)-[:DECLARES]->(dependency:Maven:Dependency)-[:TO_ARTIFACT]->(:Maven:Artifact),
  (dependency)-[:EXCLUDES]->(:Maven:Exclusion)

== 1.8.0

* Added plugin configuration options for scanning artifacts that are declared as dependencies to a Maven project (https://github.com/jQAssistant/jqa-maven3-plugin/issues/10[issue])
** `maven3.dependencies.scan` for enabling scanning dependencies
** `maven3.dependencies.includes` and `maven3.dependencies.excludes` taking Maven artifact filters to control which artifact should be scanned
* Added capability to scan URLs as part of scanIncludes

== 1.7.0

* Added a label `Effective` for `:Maven:Pom` nodes to represent the effective model of a project or artifact
* Fixed a problem where in a multi module Maven project resolved dependencies between artifacts have been created multipe times
* Improved graph model to support for exclusions on declared or managed dependencies:

  (:Pom)-[:DECLARES]->(dependency:Maven:Dependency)-[:TO_ARTIFACT]->(:Maven:Artifact),
  (dependency)-[:EXCLUDES]->(:Maven:Exclusion)

NOTE: The previously used graph model `(:Pom)-[:DECLARES_DEPENDENCY]\->(:Maven:Artifact)` is still supported but deprecated.
 It will be removed in upcoming releases.

* Fixed Maven project scanner to add label `:File` only to `:Maven:Artifact` nodes if the corresponding Maven artifact has been scanned
* Upgraded Maven core and plugin dependencies to Maven 3.5.0

== 1.6.0

* Resolve the dependency tree for the artifacts generated by a Maven project which can be queried by
  ```MATCH (p:Maven:Project)-[:CREATES]->(a:Artifact)-[:DEPENDS_ON*]->(d:Artifact) RETURN *```
* Added to the documentation that the declared dependencies of a Maven plugin
  can be queried by using the outgoing `DECLARES_DEPENDENCY` relation of
  the node for a Maven plugin.
* The information of the SCM (Source Control Management) section of a POM
  is now also part of the graph model. The node for the SCM information
  can be queried with a query like `MATCH (p:Maven:Pom)-[:HAS_SCM]\->(s:Maven:Scm) RETURN s`.
* The URL of the project home is now available as property of the node for the Maven POM
  and can be retrieved via the property `url`. A query to access the project home
  could be written as `MATCH (p:Maven:Pom) RETURN p.url`.

== 1.5.0

* The Maven project scanner adds a label `Main` to the main artifact (e.g. classes compiled from `src/main/java`) and `Test` to the test artifact ((e.g. classes compiled from `src/test/java`)

== 1.4

* Fixed wrong compiler settings to generate Java 7 bytecode instead of Java 8

== 1.3

* The plugin adds now also information on the organization behind
  a project to the generated graph. See
  https://github.com/buschmais/jqa-maven3-plugin/issues/3[Support for Organization information^]
  on GitHub.

== 1.2

* Maven coordinates changed from `com.buschmais.jqassistant.plugin:jqassistant.plugin.maven3`
  to `com.buschmais.jqassistant.plugin:maven3`.
* No functional changes since version 1.1.3.



