== 1.0.0-RC1

=== Core

==== General
- reduced amount of log messages printed on the console while running

==== Scanner
- introduced pluggable scopes for identifying file and url types, e.g. 'maven:repository' or 'java:classpath'

==== Rules
- added support for writing rules using AsciiDoc
- added support for rules written in script languages (e.g. Ruby, Groovy, JavaScript etc.) using the Java Scripting API
  (JSR-223)


=== Maven plugin
- minimum requirement has been changed to Apache Maven 3.2.x
- added support for scopes: scope element in scanIncludes and a new goal available-scopes
- allow multi-threaded maven builds

=== Command line
- added command line support for scopes, e.g. scan -f java:classpath::/My/ClassPath/

=== Plugins

==== Facelet
- added facelet plugin providing a scanner for JSF 2.x XHTML based views

==== Java
- scanner adds DEPENDS_ON relations between Java types during scan, the corresponding concepts have been removed
- referenced Java types are only resolved within the same artifact or dependencies thereof, unresolvable types will be
  referenced by a REQUIRES relation from the artifact.

==== Java EE 6
- added scanners for EAR archives and application.xml descriptors
- added scanners for WAR archives and web.xml descriptors

==== JUnit
- renamed JUnit4 plugin to JUnit as it also contains rules for JUnit3
- added a concept 'junit4:SuiteClass'
- added a group 'junit4:Default' including all defined constraints for JUnit4

==== Maven
- added a plugin for scanning pom.xml files providing access to dependency management, plugins, profiles, etc.

==== Maven Repository
- added Maven 2 Repository plugin (m2repo) containing a scanner for incremental scans of remote repositories

==== RDBMS
- added RDBMS plugin containing a scanner to import schema metadata from relational databases

==== TestNG
- added TestNG plugin containing concepts

==== XML
- added XML plugin containing a generic scanner for XML files

=== Plugin API
- added annotation @Requires for scanner plugins to build dependency chains
- added mandatory "name" attribute to jqassistant-plugin element of jqassistant-plugin.xml descriptors
- moved file related model classes from package 'c.b.j.core.store.api.model' to 'c.b.j.plugin.common.api.model'
