== 1.1.1

=== Core
- Upgraded to Neo4j 2.3.1
- If a rule could not be executed the file name containing it is now part of the error message
- Fixed rendering of an overridden severity for reporting a violation

=== Maven
- fixed a bug where analyze and server goals were not executed at the end of a multi-module reactor if one of the modules defined the property "jqassistant.skip"

=== Plugins

==== Common
- Use Apache commons compress for handling ZIP files for more robust handling of different encodings

==== Java
- If an artifact requires a Java type (i.e. an external class reference) then an existing node of that type which is already
  required by a dependency will be re-used to reduce the number of generated nodes and avoid duplicates
- Fixed concept dependency:Artifact to create unique relations
- Fixed a problem that occurred while scanning invalid class files

==== JPA2
- added support for scanning persistence.xml v2.1 documents

==== Maven
- Fixed a problem that occurred where while scanning a reduced pom.xml file generated by the Maven shade plugin

