== Quickstart

=== Command Line

==== Requirements

- Java Development Kit 11 or later
- optional _JAVA_HOME_ environment variable pointing to the JDK to be used for jQAssistant

==== Installation

* The latest command line distributions are available on Maven Central. Use one of the links below for selecting the bundled Neo4j version depending on your local JDK, select `Browse` and download the `*-distribution.zip` file:
** https://central.sonatype.com/artifact/com.buschmais.jqassistant.cli/jqassistant-commandline-neo4jv5/versions[jQAssistant for JDK 17 or later] (includes Neo4j v5.x, _recommended_)
** https://central.sonatype.com/artifact/com.buschmais.jqassistant.cli/jqassistant-commandline-neo4jv4/versions[jQAssistant for JDK 11] (includes Neo4j v4.x)
* Unpack the distribution, a directory `jqassistant-commandline-neo4jv__<?>__-_<version>_` will be created.
It contains a `bin` folder providing `jqassistant` shell scripts for Windows and Linux systems.

[TIP]
====
The Neo4j v5.x command line distribution is also available via https://sdkman.io/[SDKMan!]:

[source,bash]
----
sdk install jqassistant
----
====

==== Scan

[source,bash]
----
jqassistant scan -f lib
----

* The JAR files contained in the lib/ folder will be scanned.

==== Explore

[source,bash]
----
jqassistant server
----

* Open a browser and navigate to http://localhost:7474/?dbms=bolt://localhost:7687&preselectAuthMethod=NO_AUTH[http://localhost:7474/?dbms=bolt://localhost:7687&preselectAuthMethod=NO_AUTH] (see also <<open-browser>>)
* Enter the following query in the top level area and hit Ctrl-Enter:

[source]
----
MATCH
  (a:Artifact)-[:CONTAINS]->(t:Type)-[:DECLARES]->(m:Method)
RETURN
  a.fileName as Artifact, t.fqn AS Type, count(t) AS DeclaredMethods
ORDER BY
  DeclaredMethods DESC
LIMIT 20
----

=== Maven

==== Requirements

- Maven 3.5 or later
- Java Development Kit 11 or later

==== Add the plugin

Add the following lines to the parent pom.xml file of your project:

[source,xml,subs=attributes+]
----
<project>
    <properties>
        <!-- Define your desired jQAssistant version here -->
        <jqassistant.version>{projectVersion}</jqassistant.version>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>com.buschmais.jqassistant</groupId>
                <artifactId>jqassistant-maven-plugin</artifactId>
                <version>${jqassistant.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>scan</goal>
                            <goal>analyze</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
----

==== Add a rule

Within your parent module create a directory `jqassistant` and a file `my-rules.xml`:

[source,xml]
.jqassistant/my-rules.xml
----
<jqassistant-rules xmlns="http://schema.jqassistant.org/rule/v2.8"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://schema.jqassistant.org/rule/v2.8 https://jqassistant.github.io/jqassistant/current/schema/jqassistant-rule-v2.8.xsd">

    <group id="default">
        <includeConstraint refId="my-rules:*"/>
    </group>

    <constraint id="my-rules:TestClassWithoutTestSuffix">
        <requiresConcept refId="java:TestMethod"/>
        <description>A class declaring test methods must have the name suffix "Test".</description>
        <cypher><![CDATA[
            MATCH
              (testClass:Java:Type)-[:DECLARES]->(testMethod:Test:Method)
            WHERE NOT
              testClass.name ends with "Test"
            RETURN DISTINCT
              testClass AS TestClassWithoutTestSuffix
        ]]></cypher>
    </constraint>
</jqassistant-rules>
----

==== Run the build

Execute the following command from your parent module:

[source]
----
mvn install
----

The build will fail with the rule's message if it is violated.

The HTML report generated from the Asciidoc file including all results is available from `target/jqassistant/report/asciidoc/index.html`.

==== Explore your application

jQAssistant comes with an integrated Neo4j server, you can run it using

[source]
----
mvn jqassistant:server
----

* Open a browser and navigate to http://localhost:7474/?dbms=bolt://localhost:7687&preselectAuthMethod=NO_AUTH[http://localhost:7474/?dbms=bolt://localhost:7687&preselectAuthMethod=NO_AUTH] (see also <<open-browser>>)
* Enter the follwoing query in the top level area and hit Ctrl-Enter:

[source]
----
MATCH
  (t:Type)-[:DECLARES]->(m:Method)
RETURN
  t.fqn AS Type, count(t) AS DeclaredMethods
ORDER BY
  DeclaredMethods DESC
LIMIT 20
----

[[open-browser]]
[TIP,reftext="Tip: Open browser when starting embedded server"]
====
The embedded server by default is started to listen by default on URI `bolt://localhost:7687` without authentication.
jQAssistant can open the Neo4j browser in your desktop browser automatically when running the server by activating `jqassistant.server.open-browser`, e.g. by using a `jqassistant.yml` in your home directory:

[source,yaml]
.~/.jqassistant.yml
----
jqassistant:
  server:
    open-browser: true
----
====
