package com.buschmais.jqassistant.plugin.javaee6.api.model;

import com.buschmais.jqassistant.core.store.api.model.Descriptor;
import com.buschmais.xo.api.annotation.Abstract;
import com.buschmais.xo.neo4j.api.annotation.Label;

/**
 * Defines label "Jsf" which is applied to all nodes generated by this plugin.
 *
 * @author peter.herklotz@buschmais.com
 */
@Label("Jsf")
@Abstract
public interface JsfDescriptor extends Descriptor {
}
