==== AsciiDoc

This example demonstrates the definition of rules in AsciiDoc documents and rendering them to an HTML documentation for
developers.

Therefore a Maven project is used with the following structure:

.Project structure
[source]
----
|-pom.xml
|
|-jqassistant
|           |-index.adoc
|
|-src/main/java
              |-com.buschmais.jqassistant.examples.rules.asciidoc.api
              |-com.buschmais.jqassistant.examples.rules.asciidoc.impl
----

The pom.xml file includes the setup for the jQAssistant Maven plugin and the Asciidoctor Maven Plugin:

[source,xml]
.jqassistant/index.adoc
----
include::{docRoot}/jqassistant.examples.rules.asciidoc/src/pom.xml[tags=build]
----

The file "jqassistant/index.adoc" provides the following definitions:

The group "default"::
  A group can be applied to any block in the document, e.g. a head line, a list, etc by adding a role attribute with value
  "group". The attributes "includeGroups", "includesConcepts" and "includesConstraints" reference the rules which should
  be included and are given as comma separated lists of their ids. For concepts and constraints their default severity may
  be overwritten.

The concepts "module-structure:Api", "module-structure:Impl" and the constraint "module-structure:ApiMustNotDependOnImplementation"::
  Concepts and constraints are code blocks (i.e. cypher) with a role attribute being either "concept" or "constraint". Further
  allowed attributes are "severity" and "requiresConcepts".

[source]
.jqassistant/index.adoc
....
include::{docRoot}/jqassistant.examples.rules.asciidoc/src/jqassistant/index.adoc[]
....

The AsciiDoc document renders to the following output:

.target/generated-docs/index.html
===============
include::{docRoot}/jqassistant.examples.rules.asciidoc/src/jqassistant/index.adoc[]
===============


