assert new File(basedir, 'module1/target/jqassistant/jqassistant-report.xml').exists()
assert new File(basedir, 'module2/target/jqassistant/jqassistant-report.xml').exists()
assert new File(basedir, 'module1/target/surefire-reports/TEST-default.xml').exists()
assert new File(basedir, 'module2/target/surefire-reports/TEST-default.xml').exists()
assert new File(basedir, 'module1/target/site/jqassistant.html').exists()
assert new File(basedir, 'module2/target/site/jqassistant.html').exists()