== Command Line

Shell scripts are provided for executing jQAssistant from the command line of Microsoft Windows(R) or Unix compatible
systems. They are located in the bin/ directory of the distribution:

* jqassistant.cmd
* jqassistant.sh

The command line accepts tasks and their specific options:

[source]
----
jqassistant.sh <task1> <task2> <task3> -<option1> -<option2>
----

The following example will scan the content of the directories classes/ and test-classes/:

[source]
----
jqassistant.sh scan -f classes,test-classes
----

=== Configuration

The recommended way of configuring jQAssistant is using a file `.jqassistant.yml` located in the working directory.
Available options are described in the section <<core:Configuration>>.

Furthermore, the following command line specific configuration properties are supported:

[source,yaml]
----
jqassistant:

  # Defines the local and remote Maven repositories for retrieving additional plugins.
  repositories:
    # The path to the local repository.
    #
    # -Djqassistant.repositories.local (optional)
    local: ~/.jqassistant/repository
    remotes:
      central:
        # The URL of the Maven repository
        #
        # -Djqassistant.repositories.central.url
        url:
        # The user name for authenticating against the repository
        #
        # -Djqassistant.repositories.central.username (optional)
        username:
        # The password for authenticating against the repository
        #
        # -Djqassistant.repositories.central.password (optional)
        password:

  # The optional proxy to use for downloading additional plugins
  proxy:
    # The protocol of the proxy
    #
    # -Djqassistant.proxy.protocol (optional)
    protocol: https
    # The proxy host
    #
    # -Djqassistant.proxy.host
    host:
    # The proxy port
    #
    # -Djqassistant.proxy.port
    port:
    # The list of hosts which should not be proxied, separated by ',' or '|', the wildcard '*' is allowed.
    #
    # -Djqassistant.proxy.non-proxy-hosts (optional)
    non-proxy-hosts:
    # The proxy password for authentication
    #
    # -Djqassistant.proxy.password (optional)
    password:
----

NOTE: Plugins will be downloaded using the configured local and remote Maven repositories (default:
Maven Central). If a file `~/.m2/settings.xml` exists (i.e. user specific Maven settings) the configuration from there will be used including mirrors and proxies as well as repositories, pluginRepositories and properties from active profiles.

=== Options

[[cli:configurationLocations]]
* -configurationLocations <files> <directories>
** the list of configuration locations, e.g. YAML files and directories
** default: '.jqassistant.yml, .jqassistant.yaml, .jqassistant/\*.yml, .jqassistant/**.yaml'

[[cli:mavenSettings]]
* -mavenSettings <file>
** the location of a Maven settings.xml file to use for repository, proxy and mirror configurations

[[cli:configurationProperty]]
* -D key1=value1 [-D key2=value]
** one or more configuration properties to extend or overwrite the existing configuration

=== Tasks

* <<cli:analyze>>
* <<cli:available-rules>>
* <<cli:available-scopes>>
* <<cli:effective-configuration>>
* <<cli:effective-rules>>
* <<cli:list-plugins>>
* <<cli:report>>
* <<cli:scan>>
* <<cli:server>>

[[cli:scan]]
==== scan

Scans files or directories and stores the gathered information in database. Files or URLs are accepted and may be
specified further by scopes, e.g.

[source]
----
jqassistant.sh scan -f lib/
jqassistant.sh scan -f java:classpath::classes/
jqassistant.sh scan -u http://host/artifact.jar
jqassistant.sh scan -u http://user:secret@host/artifact.jar
jqassistant.sh scan -u maven:repository::http://my.maven.repository
----

[[cli:available-scopes]]
==== available-scopes

List all available scopes which may be specified for scanning.

[[cli:analyze]]
==== analyze

Executes an analysis.

[[cli:available-rules]]
==== available-rules

List all available rules.

[[cli:effective-configuration]]
==== effective-configuration

Print the current configuration as YAML representation on the console.

[[cli:effective-rules]]
==== effective-rules

List the rules which would be executed for an analysis and the given concepts, constraints or groups.

[[cli:list-plugins]]
==== list-plugins

Lists all plugins known to jQAssistant. Helpful to check
which plugins are active during the scan and analysis.

[source]
----
jqassistant.sh list-plugins
----

[[cli:report]]
==== report

Transforms an XML report into HTML.

[[cli:server]]
==== server

Starts the integrated Neo4j web server.

