
= Commandline Tool

== 1.9.0

* Added command line option `createReportArchive` to the analyze task for creating a ZIP archive containing the generated reports
* Added command line options `storeEncryption`, `storeTrustStrategy` and `storeTrustCertificate` to control encryption for bolt connections to a Neo4j database

== 1.8.0

* Added Asciidoc Report plugin to CLI distribution
* Removed commandline options `embeddedApocEnabled` `embeddedGraphAlgorithmsEnabled`.
  These are now available as separate plugins,
  see https://github.com/jqassistant-contrib/jqassistant-apoc-plugin[APOC plugin] and https://github.com/jqassistant-contrib/jqassistant-graph-algorithms-plugin[Graph Algorithms plugin]

== 1.7.0
ifdef::jqa-in-manual[== Commandline Tool 1.7.0]

* Removed Neo4j V2 distribution
* Renamed long option of `-u` for scanning URLs from `--uris` to `--urls`
* Added option `embeddedGraphAlgorithmsEnabled`

== 1.6.0

* The flag `-continueOnError` was activated by default, it is now deactivated and
   must be explicitly specified to skip errors during scanning
* Use a child-first classloading strategy for plugins, i.e. prefer classes that are provided by plugins over classes from the framework
* Removed deprecated command line option `serverAddress`, replaced by `embeddedListenAddress`
* Removed deprecated command line option `serverPort`, replaced by `embeddedHttpPort`

== 1.5.0

* Removed deprecated option `severity` from analyze task (replaced by `failOnSeverity` and `warnOnSeverity`)
* Deprecated option `serverAddress`, replaced by `embeddedListenAddress`
* Deprecated option `serverPort`, replaced by `embeddedHttpPort`
* Added options `embeddedBoltPort` and `embeddedApocEnabled`

== 1.4.0

* Two separate commandline tool distributions are now provided: Neo4jv2 (Java 7) and Neo4jv3 (Java 8+, including APOC library)
* jQAssistant now logs the severity of constraint violations
  which will cause jQAssistant to fail.
  It also logs the severity of constraint violations which will
  cause warnings.

* Added `-daemon` parameter to server task

== 1.3.0

* Maven coordinates changed from `com.buschmais.jqassistant:commandline`
  to `com.buschmais.jqassistant:jqassistant-commandline`. Therefore the name of the
  commandline distribution changed from `commandline-1.3.0.zip` to
  `jqassistant-commandline-1.3.0.zip`.
* Renamed command line option `severity` to `violationSeverity`, i.e. the threshold for exiting with an error code
  after at lease one rule has failed
* Added command line option `warnSeverity` to set the threshold for logging warnings about failed rules to the console
* Added command line options `defaultConceptSeverity`, `defaultConstraintSeverity` and `defaultGroupSeverity`
* Added command line options `storeUri`, `storeUsername` and `storePassword` for initial support of remote Neo4j 3.x databases

== 1.2.0

* Added support for rule parameters.

