<<FileResourceScanner>> <<DirectoryResourceScanner>> <<UrlScanner>>

[[FileResourceScanner]]
== File Resource Scanner
Imports file resources which may origin from scanned directories, archives or URLs.

=== Configuration

.Configuration properties
[options="header"]
|====
| Property     | Description																 | Default
| file.include | A pattern defining the files to include, the wildcards * and ? are allowed. |
| file.exclude | A pattern defining the files to exclude, the wildcards * and ? are allowed. |
|====

[[:File]]
=== :File
Represents a file.

.Properties of :File
[options="header"]
|====
| Name       | Description
| fileName   | The file name.
|====

[[DirectoryResourceScanner]]
== Directory Resource Scanner
Imports directory resources which may origin from scanned directories or archives.

[[:File:Directory]]
=== :File:Directory
Represents a directory.

.Properties of :File:Directory
[options="header"]
|====
| Name       | Description
| fileName   | The file name.
|====

[[UrlScanner]]
== Url Scanner

Imports file resources from URLs as <<:File>> nodes.

NOTE: The implementation is based on mechanism provided by Java top resolve URLs and supports common protocol schemes like `file`, `http` or `https`. Furthermore, a protocol scheme `jqassistant-plugin` is available which allows scanning file resources which are packaged within jQAssistant plugins, e.g. `jqassistant-plugin:/my-resource.xml`.
