---
name: CI

on:
  push:
    branches:
      - "1193-Integrate-SARIF-report-into-jQA-build"
      - "bugfix/*"
      - "master"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "1193-Integrate-SARIF-report-into-jQA-build"
      - "bugfix/*"
  workflow_dispatch: {}

concurrency:
  group: build-java-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: jqassistant-tooling/jqassistant-github-actions/.github/workflows/ci.yml@1193-Integrate-SARIF-report-into-jQA-build
    with:
      pages: "./manual/target/generated-docs/"
      sonar_project_key: "jqassistant_jqassistant"
      sonar_organization: "jqassistant"
      publish_sarif: true

    secrets:
      ossrh_username: ${{ secrets.OSSRH_USERNAME }}
      ossrh_password: ${{ secrets.OSSRH_PASSWORD }}
      ossrh_signing_key: ${{ secrets.OSSRH_SIGNING_KEY }}
      ossrh_signing_password: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      sonarcloud_token: ${{ secrets.SONARCLOUD_TOKEN }}
      github_token: ${{ secrets.GITHUB_TOKEN }}
      confluence_username: ${{ secrets.CONFLUENCE_USERNAME }}
      confluence_password: ${{ secrets.CONFLUENCE_PASSWORD }}
