---
name: Release

on:
  workflow_dispatch:
    inputs:
      java_version:
        description: Java version to use
        type: string
        required: false
        default: 17
      branch:
        description: "The branch to checkout when cutting the release."
        required: true
        default: "master"
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      releaseAssets:
        description: "Paths to the release assets."
        required: true
        default: "[cli/neo4jv4/*-distribution.zip , cli/neo4jv5/*-distribution.zip]"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"
      dryRun:
        description: "Dry run mode (true/false)"
        required: false
        default: "true"

jobs:
  build:
    uses: jqassistant-tooling/jqassistant-github-actions/.github/workflows/release.yml@main
    with:
      branch: ${{ github.event.inputs.branch }}
      releaseVersion: ${{ github.event.inputs.releaseVersion }}
      developmentVersion: ${{ github.event.inputs.developmentVersion }}
      dryRun: ${{ github.event.inputs.dryRun }}
    secrets:
      ossrh_username: ${{ secrets.OSSRH_USERNAME }}
      ossrh_password: ${{ secrets.OSSRH_PASSWORD }}
      ossrh_signing_key: ${{ secrets.OSSRH_SIGNING_KEY }}
      ossrh_signing_password: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}

  attach-artifacts:
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Upload Release Asset Neo4j
         uses: actions/upload-artifact@v3
         with:
           name: neo4j.zip
           path: |
            cli/neo4jv4/*-distribution.zip
            cli/neo4jv5/*-distribution.zip
           content_type: application/zip
