---
name: Release

on:
  workflow_dispatch:
    inputs:
      java_version:
        description: Java version to use
        type: string
        required: false
        default: 17
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"
      dryRun:
        description: "Perform a dry run"
        required: true
        default: false
        type: boolean
      assets:
        description: "Path expression for Assets to upload."
        type: string
        required: false
        default: "target/checkout/cli/neo4jv?/target/*-distribution.zip"
      pages:
        description: "Path expression for Pages to upload."
        required: false
        default: "./manual/target/generated-docs/"
      deployCurrentDoc:
        description: "Deploy the current documentation page."
        type: boolean
        required: false
        default: false

jobs:
  build:
    uses: jqassistant-tooling/jqassistant-github-actions/.github/workflows/release.yml@main
    with:
      releaseVersion: ${{ github.event.inputs.releaseVersion }}
      developmentVersion: ${{ github.event.inputs.developmentVersion }}
      dryRun: ${{ github.event.inputs.dryRun }}
      assets: ${{ github.event.inputs.assets }}
      pages: ${{ github.event.inputs.pages }}
      deployCurrentDoc: ${{ github.event.inputs.deployCurrentDoc }}
    secrets:
      ossrh_username: ${{ secrets.OSSRH_USERNAME }}
      ossrh_password: ${{ secrets.OSSRH_PASSWORD }}
      ossrh_signing_key: ${{ secrets.OSSRH_SIGNING_KEY }}
      ossrh_signing_password: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
