---
name: Release

on:
  workflow_dispatch:
    inputs:
      java_version:
        description: Java version to use
        type: string
        required: false
        default: 17
      branch:
        description: "The branch to checkout when cutting the release."
        required: true
        default: "479-command-line-distributions-shall-be-attached-to-github-releases"
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"
      dryRun:
        description: "Perform a dry run"
        required: true
        default: false
        type: boolean
      neo4j:
        description: "Neo4j v4 version to use"
        type: string
        required: true
        default: 'cli/neo4jv4/target/*-distribution.zip'


jobs:
  build:
    uses: jqassistant-tooling/jqassistant-github-actions/.github/workflows/release.yml@neo4j-release
    with:
      branch: ${{ github.event.inputs.branch }}
      releaseVersion: ${{ github.event.inputs.releaseVersion }}
      developmentVersion: ${{ github.event.inputs.developmentVersion }}
      dryRun: ${{ github.event.inputs.dryRun }}
      neo4j: ${{ github.event.inputs.neo4j }}
    secrets:
      ossrh_username: ${{ secrets.OSSRH_USERNAME }}
      ossrh_password: ${{ secrets.OSSRH_PASSWORD }}
      ossrh_signing_key: ${{ secrets.OSSRH_SIGNING_KEY }}
      ossrh_signing_password: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
