---
name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'The release version'
        required: true
      developmentVersion:
        description: 'The development version'
        required: true
      dryRun:
        description: 'Whether to perform a dry run'
        required: true
        default: 'false'
        type: boolean

jobs:
  dry-run:
    if: ${{ github.event.inputs.dryRun }}
    runs-on: ubuntu-latest
    steps:
      - name: Perform Dry Run
        run: |
          mvn release:prepare release:perform \
          -ntp \
          --batch-mode \
          -DreleaseVersion=${{ inputs.releaseVersion }} \
          -DdevelopmentVersion=${{ inputs.developmentVersion }} \
          -DdryRun=${{ inputs.dryRun }}
  build:
    needs: dry-run
    uses: jqassistant-tooling/jqassistant-github-actions/.github/workflows/release.yml@main
    with:
      branch: ${{ github.event.inputs.branch }}
      releaseVersion: ${{ github.event.inputs.releaseVersion }}
      developmentVersion: ${{ github.event.inputs.developmentVersion }}
      dryRun: ${{ github.event.inputs.dryRun }}
    secrets:
      ossrh_username: ${{ secrets.OSSRH_USERNAME }}
      ossrh_password: ${{ secrets.OSSRH_PASSWORD }}
      ossrh_signing_key: ${{ secrets.OSSRH_SIGNING_KEY }}
      ossrh_signing_password: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
