def buildLog = new File(basedir, 'build.log')
assert buildLog.exists()

assert buildLog.getText().contains("""jQAssistant Common Plugin (jqa.plugin.common)""")
assert buildLog.getText().contains("""jQAssistant Core Analysis Plugin (jqa.core.analysis.plugin)""")
assert buildLog.getText().contains("""jQAssistant Core Report Plugin (jqa.core.report.plugin)""")
assert buildLog.getText().contains("""jQAssistant Java Plugin (jqa.plugin.java)""")
assert buildLog.getText().contains("""jQAssistant JSON Plugin (jqa.plugin.json)""")
assert buildLog.getText().contains("""jQAssistant JUnit Plugin (jqa.plugin.junit)""")
assert buildLog.getText().contains("""jQAssistant Maven 3 Plugin (jqa.plugin.maven3)""")
assert buildLog.getText().contains("""jQAssistant XML Plugin (jqa.plugin.xml)""")
assert buildLog.getText().contains("""jQAssistant YAML 2 Plugin (jqa.plugin.yaml2)""")
