def buildLog = new File(basedir, 'build.log')
assert buildLog.exists()

assert buildLog.getText().contains("""jQAssistant CDI Plugin (jqa.plugin.cdi)""")
assert buildLog.getText().contains("""jQAssistant AsciiDoc Report Plugin (jqa.plugin.asciidocreport)""")
assert buildLog.getText().contains("""jQAssistant CDI Plugin (jqa.plugin.cdi)""")
assert buildLog.getText().contains("""jQAssistant Common Plugin (jqa.plugin.common)""")
assert buildLog.getText().contains("""jQAssistant Core Analysis Plugin (jqa.core.analysis.plugin)""")
assert buildLog.getText().contains("""jQAssistant Core Report Plugin (jqa.core.report.plugin)""")
assert buildLog.getText().contains("""jQAssistant EJB 3 Plugin (jqa.plugin.ejb)""")
assert buildLog.getText().contains("""jQAssistant GraphML Plugin (jqa.plugin.graphml)""")
assert buildLog.getText().contains("""jQAssistant GraphQL Plugin (jqa.plugin.graphql)""")
assert buildLog.getText().contains("""jQAssistant Java EE 6 Plugin (jqa.plugin.javaee)""")
assert buildLog.getText().contains("""jQAssistant Java Plugin (jqa.plugin.java)""")
assert buildLog.getText().contains("""jQAssistant JAX-RS Plugin (jqa.plugin.jaxrs)""")
assert buildLog.getText().contains("""jQAssistant JPA 2 Plugin (jqa.plugin.jpa2)""")
assert buildLog.getText().contains("""jQAssistant JSON Plugin (jqa.plugin.json)""")
assert buildLog.getText().contains("""jQAssistant JUnit Plugin (jqa.plugin.junit)""")
assert buildLog.getText().contains("""jQAssistant Maven 2 Repository Plugin (jqa.plugin.m2repo)""")
assert buildLog.getText().contains("""jQAssistant Maven 3 Plugin (jqa.plugin.maven3)""")
assert buildLog.getText().contains("""jQAssistant OSGi Plugin (jqa.plugin.osgi)""")
assert buildLog.getText().contains("""jQAssistant RDBMS Plugin (jqa.plugin.rdbms)""")
assert buildLog.getText().contains("""jQAssistant Spring Plugin (jqa.plugin.spring)""")
assert buildLog.getText().contains("""jQAssistant TestNG Plugin (jqa.plugin.testng)""")
assert buildLog.getText().contains("""jQAssistant Tycho Plugin (jqa.plugin.tycho)""")
assert buildLog.getText().contains("""jQAssistant XML Plugin (jqa.plugin.xml)""")
assert buildLog.getText().contains("""jQAssistant YAML 2 Plugin (jqa.plugin.yaml2)""")
